// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Sample
{
    public partial class GetCITDenominationByDatesResult
    {
        public string tx_currency { get; set; }
        public int denom { get; set; }
        public long? count { get; set; }
        public long? subtotal { get; set; }
    }
}
