// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    /// <summary>
    /// Types of messages for alerts sent via email or phone
    /// </summary>
    [Table("AlertMessageType")]
    [Index("Rowguid", Name = "MSmerge_index_1968778121", IsUnique = true)]
    public partial class AlertMessageType
    {
        public AlertMessageType()
        {
            AlertEvents = new HashSet<AlertEvent>();
            AlertMessageRegistries = new HashSet<AlertMessageRegistry>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        /// <summary>
        /// Name of the AlertMessage
        /// </summary>
        [Required]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }
        [Column("description")]
        [StringLength(255)]
        public string Description { get; set; }
        /// <summary>
        /// Title displayed in th eheader sction of messages
        /// </summary>
        [Column("title")]
        [StringLength(255)]
        public string Title { get; set; }
        /// <summary>
        /// The HTML template that will be merged into later
        /// </summary>
        [Column("email_content_template")]
        public string EmailContentTemplate { get; set; }
        /// <summary>
        /// The raw text template that will be merged into later
        /// </summary>
        [Column("raw_email_content_template")]
        public string RawEmailContentTemplate { get; set; }
        /// <summary>
        /// The SMS template that will be merged into later
        /// </summary>
        [Column("phone_content_template")]
        [StringLength(255)]
        public string PhoneContentTemplate { get; set; }
        /// <summary>
        /// whether or not the alert message type in enabled and can be instantiated
        /// </summary>
        [Required]
        [Column("enabled")]
        public bool? Enabled { get; set; }
        [Column("rowguid")]
        public Guid Rowguid { get; set; }

        [InverseProperty("AlertType")]
        public virtual ICollection<AlertEvent> AlertEvents { get; set; }
        [InverseProperty("AlertType")]
        public virtual ICollection<AlertMessageRegistry> AlertMessageRegistries { get; set; }
    }
}