// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    [Table("ApplicationUser")]
    [Index("Email", Name = "UX_ApplicationUser_Email", IsUnique = true)]
    [Index("Username", Name = "UX_ApplicationUser_Username", IsUnique = true)]
    [Index("RoleId", Name = "irole_id_ApplicationUser")]
    [Index("UserGroup", Name = "iuser_group_ApplicationUser")]
    public partial class ApplicationUser
    {
        public ApplicationUser()
        {
            ApplicationUserChangePasswords = new HashSet<ApplicationUserChangePassword>();
            CitAuthUserNavigations = new HashSet<Cit>();
            CitStartUserNavigations = new HashSet<Cit>();
            DeviceLocks = new HashSet<DeviceLock>();
            PasswordHistories = new HashSet<PasswordHistory>();
            UserLockLockingUserNavigations = new HashSet<UserLock>();
            UserLockUsers = new HashSet<UserLock>();
        }

        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        /// <summary>
        /// username for logging into the system
        /// </summary>
        [Required]
        [Column("username")]
        [StringLength(255)]
        public string Username { get; set; }
        /// <summary>
        /// salted and hashed password utilising a password library
        /// </summary>
        [Required]
        [Column("password")]
        [StringLength(71)]
        [Unicode(false)]
        public string Password { get; set; }
        /// <summary>
        /// First names
        /// </summary>
        [Required]
        [Column("fname")]
        [StringLength(50)]
        public string Fname { get; set; }
        /// <summary>
        /// Last name
        /// </summary>
        [Required]
        [Column("lname")]
        [StringLength(50)]
        public string Lname { get; set; }
        /// <summary>
        /// The role the user has e.g. Custodian, Branch Manager tc
        /// </summary>
        [Column("role_id")]
        public Guid RoleId { get; set; }
        /// <summary>
        /// user email address, used to receive emails from the system
        /// </summary>
        [Required]
        [Column("email")]
        [StringLength(50)]
        public string Email { get; set; }
        /// <summary>
        /// whether or not the user is allowed to receive emails
        /// </summary>
        [Required]
        [Column("email_enabled")]
        public bool? EmailEnabled { get; set; }
        /// <summary>
        /// the phone number for the user to rceive SMSes from the system
        /// </summary>
        [Column("phone")]
        [StringLength(50)]
        public string Phone { get; set; }
        /// <summary>
        /// can the user receive SMSes from the system
        /// </summary>
        [Column("phone_enabled")]
        public bool PhoneEnabled { get; set; }
        /// <summary>
        /// should the user rset their password at their next login
        /// </summary>
        [Column("password_reset_required")]
        public bool PasswordResetRequired { get; set; }
        /// <summary>
        /// is the current user locked out of the device?
        /// </summary>
        [Column("is_locked")]
        public bool IsLocked { get; set; }
        /// <summary>
        /// how many unsuccessful login attempts has the user mad in a row. used to lock the user automatically
        /// </summary>
        [Column("login_attempts")]
        public int LoginAttempts { get; set; }
        [Column("user_group")]
        public int UserGroup { get; set; }

        [ForeignKey("RoleId")]
        [InverseProperty("ApplicationUsers")]
        public virtual Role Role { get; set; }
        [ForeignKey("UserGroup")]
        [InverseProperty("ApplicationUsers")]
        public virtual UserGroup UserGroupNavigation { get; set; }
        [InverseProperty("UserNavigation")]
        public virtual ICollection<ApplicationUserChangePassword> ApplicationUserChangePasswords { get; set; }
        [InverseProperty("AuthUserNavigation")]
        public virtual ICollection<Cit> CitAuthUserNavigations { get; set; }
        [InverseProperty("StartUserNavigation")]
        public virtual ICollection<Cit> CitStartUserNavigations { get; set; }
        [InverseProperty("LockingUserNavigation")]
        public virtual ICollection<DeviceLock> DeviceLocks { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<PasswordHistory> PasswordHistories { get; set; }
        [InverseProperty("LockingUserNavigation")]
        public virtual ICollection<UserLock> UserLockLockingUserNavigations { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<UserLock> UserLockUsers { get; set; }
    }
}