// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    /// <summary>
    /// currency and deomination breakdown of the CIT bag
    /// </summary>
    [Table("CITDenominations")]
    [Index("CitId", Name = "icit_id_CITDenominations")]
    [Index("CurrencyId", Name = "icurrency_id_CITDenominations")]
    public partial class Citdenomination
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        /// <summary>
        /// The CIT the record belongs to
        /// </summary>
        [Column("cit_id")]
        public Guid CitId { get; set; }
        /// <summary>
        /// When this item was recorded
        /// </summary>
        [Column("datetime")]
        public DateTime? Datetime { get; set; }
        /// <summary>
        /// The currency code
        /// </summary>
        [Required]
        [Column("currency_id")]
        [StringLength(3)]
        [Unicode(false)]
        public string CurrencyId { get; set; }
        /// <summary>
        /// denomination of note or coin in major currency
        /// </summary>
        [Column("denom")]
        public int Denom { get; set; }
        /// <summary>
        /// How many of the denomination were counted
        /// </summary>
        [Column("count")]
        public int Count { get; set; }
        /// <summary>
        /// The subtotal of the denomination calculated as denom*count
        /// </summary>
        [Column("subtotal")]
        public int Subtotal { get; set; }

        [ForeignKey("CitId")]
        [InverseProperty("Citdenominations")]
        public virtual Cit Cit { get; set; }
        [ForeignKey("CurrencyId")]
        [InverseProperty("Citdenominations")]
        public virtual Currency Currency { get; set; }
    }
}