// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    [Keyless]
    public partial class Citview
    {
        [Column("cit_date")]
        public DateTime CitDate { get; set; }
        [Required]
        [Column("Device-Name")]
        [StringLength(50)]
        [Unicode(false)]
        public string DeviceName { get; set; }
        [Required]
        [Column("Branch-Name")]
        [StringLength(50)]
        public string BranchName { get; set; }
        [Column("Sub-Total")]
        public int? SubTotal { get; set; }
        [Column("Denom:-50")]
        public int Denom50 { get; set; }
        [Column("Denom:-100")]
        public int Denom100 { get; set; }
        [Column("Denom:-200")]
        public int Denom200 { get; set; }
        [Column("Denom:-500")]
        public int Denom500 { get; set; }
        [Column("Denom:-1000")]
        public int Denom1000 { get; set; }
        [Column("fromDate")]
        public DateTime? FromDate { get; set; }
        [Column("toDate")]
        public DateTime ToDate { get; set; }
        [Column("old_bag_number")]
        [StringLength(50)]
        public string OldBagNumber { get; set; }
        [Column("new_bag_number")]
        [StringLength(50)]
        public string NewBagNumber { get; set; }
        [Column("seal_number")]
        [StringLength(50)]
        public string SealNumber { get; set; }
        [Column("complete")]
        public bool Complete { get; set; }
        [Column("cit_complete_date")]
        public DateTime? CitCompleteDate { get; set; }
        [Column("cit_error")]
        public int CitError { get; set; }
        [Column("cit_error_message")]
        [StringLength(255)]
        public string CitErrorMessage { get; set; }
        [Column("device_id")]
        public Guid DeviceId { get; set; }
        [Column("Device-ID")]
        public Guid DeviceId1 { get; set; }
        [Column("Branch-ID")]
        public Guid BranchId { get; set; }
    }
}