// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    /// <summary>
    /// Configuration list
    /// </summary>
    [Table("Config")]
    [Index("Rowguid", Name = "MSmerge_index_1853210348", IsUnique = true)]
    [Index("CategoryId", Name = "icategory_id_Config")]
    public partial class Config
    {
        public Config()
        {
            DeviceConfigs = new HashSet<DeviceConfig>();
        }

        [Key]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }
        [Column("default_value")]
        public string DefaultValue { get; set; }
        [Column("description")]
        [StringLength(255)]
        public string Description { get; set; }
        [Column("category_id")]
        public Guid CategoryId { get; set; }
        [Column("rowguid")]
        public Guid Rowguid { get; set; }

        [ForeignKey("CategoryId")]
        [InverseProperty("Configs")]
        public virtual ConfigCategory Category { get; set; }
        [InverseProperty("Config")]
        public virtual ICollection<DeviceConfig> DeviceConfigs { get; set; }
    }
}