// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    /// <summary>
    /// Group together configurations so devices can share configs
    /// </summary>
    [Table("ConfigGroup")]
    [Index("Rowguid", Name = "MSmerge_index_624721278", IsUnique = true)]
    [Index("ParentGroup", Name = "iparent_group_ConfigGroup")]
    public partial class ConfigGroup
    {
        public ConfigGroup()
        {
            DeviceConfigs = new HashSet<DeviceConfig>();
            Devices = new HashSet<Device>();
            InverseParentGroupNavigation = new HashSet<ConfigGroup>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; }
        [Column("description")]
        [StringLength(512)]
        public string Description { get; set; }
        [Column("parent_group")]
        public int? ParentGroup { get; set; }
        [Column("rowguid")]
        public Guid Rowguid { get; set; }

        [ForeignKey("ParentGroup")]
        [InverseProperty("InverseParentGroupNavigation")]
        public virtual ConfigGroup ParentGroupNavigation { get; set; }
        [InverseProperty("Group")]
        public virtual ICollection<DeviceConfig> DeviceConfigs { get; set; }
        [InverseProperty("ConfigGroupNavigation")]
        public virtual ICollection<Device> Devices { get; set; }
        [InverseProperty("ParentGroupNavigation")]
        public virtual ICollection<ConfigGroup> InverseParentGroupNavigation { get; set; }
    }
}