// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    /// <summary>
    /// contains a crash report
    /// </summary>
    [Table("CrashEvent", Schema = "exp")]
    [Index("DeviceId", Name = "idevice_id_exp_CrashEvent_7BCB8F5E")]
    public partial class CrashEvent
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("device_id")]
        public Guid DeviceId { get; set; }
        [Column("datetime")]
        public DateTime Datetime { get; set; }
        [Column("date_detected")]
        public DateTime DateDetected { get; set; }
        [Required]
        [Column("content")]
        public string Content { get; set; }

        [ForeignKey("DeviceId")]
        [InverseProperty("CrashEvents")]
        public virtual Device Device { get; set; }
    }
}