// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    [Table("DeviceSuspenseAccount")]
    [Index("DeviceId", "CurrencyCode", "TxTypeListItem", Name = "UX_Device_SuspenseAccount", IsUnique = true)]
    [Index("CurrencyCode", Name = "icurrency_code_DeviceSuspenseAccount")]
    [Index("DeviceId", Name = "idevice_id_DeviceSuspenseAccount")]
    [Index("TxTypeListItem", Name = "itx_type_listItem_DeviceSuspenseAccount")]
    public partial class DeviceSuspenseAccount
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("device_id")]
        public Guid DeviceId { get; set; }
        [Column("tx_type_listItem")]
        public int TxTypeListItem { get; set; }
        [Required]
        [Column("currency_code")]
        [StringLength(3)]
        [Unicode(false)]
        public string CurrencyCode { get; set; }
        [Required]
        [Column("account_number")]
        [StringLength(50)]
        public string AccountNumber { get; set; }
        [Column("account_name")]
        [StringLength(50)]
        public string AccountName { get; set; }
        [Column("enabled")]
        public bool Enabled { get; set; }

        [ForeignKey("CurrencyCode")]
        [InverseProperty("DeviceSuspenseAccounts")]
        public virtual Currency CurrencyCodeNavigation { get; set; }
        [ForeignKey("DeviceId")]
        [InverseProperty("DeviceSuspenseAccounts")]
        public virtual Device Device { get; set; }
        [ForeignKey("TxTypeListItem")]
        [InverseProperty("DeviceSuspenseAccounts")]
        public virtual TransactionTypeListItem TxTypeListItemNavigation { get; set; }
    }
}