// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    /// <summary>
    /// Link a Device to its configuration
    /// </summary>
    [Table("DeviceConfig")]
    [Index("ConfigId", "GroupId", Name = "UX_DeviceConfig", IsUnique = true)]
    [Index("ConfigId", Name = "iconfig_id_DeviceConfig")]
    [Index("GroupId", Name = "igroup_id_DeviceConfig")]
    public partial class DeviceConfig
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("group_id")]
        public int GroupId { get; set; }
        [Required]
        [Column("config_id")]
        [StringLength(50)]
        public string ConfigId { get; set; }
        [Required]
        [Column("value")]
        public string Value { get; set; }

        [ForeignKey("ConfigId")]
        [InverseProperty("DeviceConfigs")]
        public virtual Config Config { get; set; }
        [ForeignKey("GroupId")]
        [InverseProperty("DeviceConfigs")]
        public virtual ConfigGroup Group { get; set; }
    }
}