// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Setup.Models
{
    public partial class GetDeviceConfigByUserGroupResult
    {
        public Guid id { get; set; }
        public int group_id { get; set; }
        public string config_id { get; set; }
        public string value { get; set; }
    }
}
