// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Setup.Models
{
    public partial class GetDeviceUsersByDeviceResult
    {
        public Guid id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public Guid role_id { get; set; }
        public string email { get; set; }
        public bool email_enabled { get; set; }
        public string phone { get; set; }
        public bool phone_enabled { get; set; }
        public bool password_reset_required { get; set; }
        public bool is_locked { get; set; }
        public int login_attempts { get; set; }
        public int user_group { get; set; }
    }
}
