// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    /// <summary>
    /// Stores the text for a screen for a language
    /// </summary>
    [Table("GUIScreenText")]
    [Index("GuiscreenId", "LanguageId", Name = "UX_GUIScreenText", IsUnique = true)]
    [Index("GuiscreenId", Name = "iguiscreen_id_GUIScreenText")]
    [Index("LanguageId", Name = "ilanguage_id_GUIScreenText")]
    public partial class GuiscreenText
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        /// <summary>
        /// The GUIScreen this entry corresponds to
        /// </summary>
        [Column("guiscreen_id")]
        public int GuiscreenId { get; set; }
        /// <summary>
        /// The language this entry corresponds to
        /// </summary>
        [Required]
        [Column("language_id")]
        [StringLength(5)]
        [Unicode(false)]
        public string LanguageId { get; set; }
        /// <summary>
        /// The title heading of the screen e.g. Account Number
        /// </summary>
        [Column("screen_title")]
        [StringLength(50)]
        public string ScreenTitle { get; set; }
        /// <summary>
        /// Short instruction e.g. Enter Account Number
        /// </summary>
        [Column("screen_title_instruction")]
        [StringLength(255)]
        public string ScreenTitleInstruction { get; set; }
        /// <summary>
        /// Detailed user instructions on what to do at this screen
        /// </summary>
        [Column("full_instructions")]
        public string FullInstructions { get; set; }
        [Required]
        [Column("btn_accept_caption")]
        [StringLength(50)]
        public string BtnAcceptCaption { get; set; }
        [Required]
        [Column("btn_back_caption")]
        [StringLength(50)]
        public string BtnBackCaption { get; set; }
        [Required]
        [Column("btn_cancel_caption")]
        [StringLength(50)]
        public string BtnCancelCaption { get; set; }

        [ForeignKey("GuiscreenId")]
        [InverseProperty("GuiscreenTexts")]
        public virtual Guiscreen Guiscreen { get; set; }
        [ForeignKey("LanguageId")]
        [InverseProperty("GuiscreenTexts")]
        public virtual Language Language { get; set; }
    }
}