// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    /// <summary>
    /// A list of languages a device supports
    /// </summary>
    [Table("LanguageList")]
    [Index("DefaultLanguage", Name = "idefault_language_LanguageList")]
    public partial class LanguageList
    {
        public LanguageList()
        {
            Devices = new HashSet<Device>();
            LanguageListLanguages = new HashSet<LanguageListLanguage>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column("description")]
        [StringLength(100)]
        [Unicode(false)]
        public string Description { get; set; }
        [Required]
        [Column("enabled")]
        public bool? Enabled { get; set; }
        [Required]
        [Column("default_language")]
        [StringLength(5)]
        [Unicode(false)]
        public string DefaultLanguage { get; set; }

        [ForeignKey("DefaultLanguage")]
        [InverseProperty("LanguageLists")]
        public virtual Language DefaultLanguageNavigation { get; set; }
        [InverseProperty("LanguageListNavigation")]
        public virtual ICollection<Device> Devices { get; set; }
        [InverseProperty("LanguageListNavigation")]
        public virtual ICollection<LanguageListLanguage> LanguageListLanguages { get; set; }
    }
}