// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    [Table("ModelDifferenceAspect")]
    [Index("Gcrecord", Name = "iGCRecord_ModelDifferenceAspect")]
    [Index("Owner", Name = "iOwner_ModelDifferenceAspect")]
    public partial class ModelDifferenceAspect
    {
        [Key]
        public Guid Oid { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        public string Xml { get; set; }
        public Guid? Owner { get; set; }
        public int? OptimisticLockField { get; set; }
        [Column("GCRecord")]
        public int? Gcrecord { get; set; }

        [ForeignKey("Owner")]
        [InverseProperty("ModelDifferenceAspects")]
        public virtual ModelDifference OwnerNavigation { get; set; }
    }
}