// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    [Table("PasswordHistory")]
    [Index("UserId", Name = "iuser_id_PasswordHistory")]
    public partial class PasswordHistory
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("user_id")]
        public Guid UserId { get; set; }
        [Column("datetime")]
        public DateTime Datetime { get; set; }
        [Required]
        [Column("password")]
        [StringLength(71)]
        [Unicode(false)]
        public string Password { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("PasswordHistories")]
        public virtual ApplicationUser User { get; set; }
    }
}