// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    [Table("PermissionPolicyRole")]
    [Index("Gcrecord", Name = "iGCRecord_PermissionPolicyRole")]
    [Index("ObjectType", Name = "iObjectType_PermissionPolicyRole")]
    public partial class PermissionPolicyRole
    {
        public PermissionPolicyRole()
        {
            PermissionPolicyNavigationPermissionsObjects = new HashSet<PermissionPolicyNavigationPermissionsObject>();
            PermissionPolicyTypePermissionsObjects = new HashSet<PermissionPolicyTypePermissionsObject>();
            PermissionPolicyUserUsersPermissionPolicyRoleRoles = new HashSet<PermissionPolicyUserUsersPermissionPolicyRoleRole>();
        }

        [Key]
        public Guid Oid { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        public bool? IsAdministrative { get; set; }
        public bool? CanEditModel { get; set; }
        public int? PermissionPolicy { get; set; }
        public int? OptimisticLockField { get; set; }
        [Column("GCRecord")]
        public int? Gcrecord { get; set; }
        public int? ObjectType { get; set; }

        [ForeignKey("ObjectType")]
        [InverseProperty("PermissionPolicyRoles")]
        public virtual XpobjectType ObjectTypeNavigation { get; set; }
        [InverseProperty("RoleNavigation")]
        public virtual ICollection<PermissionPolicyNavigationPermissionsObject> PermissionPolicyNavigationPermissionsObjects { get; set; }
        [InverseProperty("RoleNavigation")]
        public virtual ICollection<PermissionPolicyTypePermissionsObject> PermissionPolicyTypePermissionsObjects { get; set; }
        [InverseProperty("RolesNavigation")]
        public virtual ICollection<PermissionPolicyUserUsersPermissionPolicyRoleRole> PermissionPolicyUserUsersPermissionPolicyRoleRoles { get; set; }
    }
}