// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    [Table("PermissionPolicyNavigationPermissionsObject")]
    [Index("Gcrecord", Name = "iGCRecord_PermissionPolicyNavigationPermissionsObject")]
    [Index("Role", Name = "iRole_PermissionPolicyNavigationPermissionsObject")]
    public partial class PermissionPolicyNavigationPermissionsObject
    {
        [Key]
        public Guid Oid { get; set; }
        public string ItemPath { get; set; }
        public int? NavigateState { get; set; }
        public Guid? Role { get; set; }
        public int? OptimisticLockField { get; set; }
        [Column("GCRecord")]
        public int? Gcrecord { get; set; }

        [ForeignKey("Role")]
        [InverseProperty("PermissionPolicyNavigationPermissionsObjects")]
        public virtual PermissionPolicyRole RoleNavigation { get; set; }
    }
}