// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    [Table("PermissionPolicyMemberPermissionsObject")]
    [Index("Gcrecord", Name = "iGCRecord_PermissionPolicyMemberPermissionsObject")]
    [Index("TypePermissionObject", Name = "iTypePermissionObject_PermissionPolicyMemberPermissionsObject")]
    public partial class PermissionPolicyMemberPermissionsObject
    {
        [Key]
        public Guid Oid { get; set; }
        public string Members { get; set; }
        public int? ReadState { get; set; }
        public int? WriteState { get; set; }
        public string Criteria { get; set; }
        public Guid? TypePermissionObject { get; set; }
        public int? OptimisticLockField { get; set; }
        [Column("GCRecord")]
        public int? Gcrecord { get; set; }

        [ForeignKey("TypePermissionObject")]
        [InverseProperty("PermissionPolicyMemberPermissionsObjects")]
        public virtual PermissionPolicyTypePermissionsObject TypePermissionObjectNavigation { get; set; }
    }
}