// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    [Table("PermissionPolicyUserUsers_PermissionPolicyRoleRoles")]
    [Index("Roles", "Users", Name = "iRolesUsers_PermissionPolicyUserUsers_PermissionPolicyRoleRoles", IsUnique = true)]
    [Index("Roles", Name = "iRoles_PermissionPolicyUserUsers_PermissionPolicyRoleRoles")]
    [Index("Users", Name = "iUsers_PermissionPolicyUserUsers_PermissionPolicyRoleRoles")]
    public partial class PermissionPolicyUserUsersPermissionPolicyRoleRole
    {
        public Guid? Roles { get; set; }
        public Guid? Users { get; set; }
        [Key]
        [Column("OID")]
        public Guid Oid { get; set; }
        public int? OptimisticLockField { get; set; }

        [ForeignKey("Roles")]
        [InverseProperty("PermissionPolicyUserUsersPermissionPolicyRoleRoles")]
        public virtual PermissionPolicyRole RolesNavigation { get; set; }
        [ForeignKey("Users")]
        [InverseProperty("PermissionPolicyUserUsersPermissionPolicyRoleRoles")]
        public virtual PermissionPolicyUser UsersNavigation { get; set; }
    }
}