// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    /// <summary>
    /// Stores details about a user lock event
    /// </summary>
    [Table("UserLock")]
    [Index("LockingUser", Name = "ilocking_user_UserLock")]
    [Index("UserId", Name = "iuser_id_UserLock")]
    public partial class UserLock
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("user_id")]
        public Guid UserId { get; set; }
        [Column("lock_date")]
        public DateTime LockDate { get; set; }
        [Column("locked")]
        public bool Locked { get; set; }
        [Column("locking_user")]
        public Guid? LockingUser { get; set; }
        [Column("web_locking_user")]
        [StringLength(50)]
        public string WebLockingUser { get; set; }
        [Column("locked_by_device")]
        public bool LockedByDevice { get; set; }

        [ForeignKey("LockingUser")]
        [InverseProperty("UserLockLockingUserNavigations")]
        public virtual ApplicationUser LockingUserNavigation { get; set; }
        [ForeignKey("UserId")]
        [InverseProperty("UserLockUsers")]
        public virtual ApplicationUser User { get; set; }
    }
}