// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    [Keyless]
    public partial class ViewPermission
    {
        [Required]
        [Column("role")]
        [StringLength(50)]
        public string Role { get; set; }
        [Required]
        [Column("activity")]
        [StringLength(50)]
        public string Activity { get; set; }
        [Column("standalone_allowed")]
        public bool StandaloneAllowed { get; set; }
        [Column("online_allowed")]
        public bool OnlineAllowed { get; set; }
        [Column("standalone_authentication_required")]
        public bool StandaloneAuthenticationRequired { get; set; }
        [Column("online_authentication_required")]
        public bool OnlineAuthenticationRequired { get; set; }
        [Column("standalone_can_Authenticate")]
        public bool StandaloneCanAuthenticate { get; set; }
        [Column("online_can_Authenticate")]
        public bool OnlineCanAuthenticate { get; set; }
    }
}