// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    [Keyless]
    public partial class ViewError
    {
        [Column("Start-Date")]
        public DateTime StartDate { get; set; }
        [Column("End-Date")]
        public DateTime? EndDate { get; set; }
        [Required]
        [Column("Branch-Name")]
        [StringLength(50)]
        public string BranchName { get; set; }
        [Required]
        [Column("Device-Name")]
        [StringLength(50)]
        [Unicode(false)]
        public string DeviceName { get; set; }
        [Required]
        [Column("Device-Location")]
        [StringLength(50)]
        public string DeviceLocation { get; set; }
        [Required]
        [Column("Transaction-Type-Name")]
        [StringLength(50)]
        public string TransactionTypeName { get; set; }
        [Column("CB-Transaction-Number")]
        [StringLength(50)]
        [Unicode(false)]
        public string CbTransactionNumber { get; set; }
        [StringLength(3)]
        [Unicode(false)]
        public string Currency { get; set; }
        [Column("Sub-Total")]
        public int? SubTotal { get; set; }
        [Column("Denomination:-50")]
        public int Denomination50 { get; set; }
        [Column("Denomination:-100")]
        public int Denomination100 { get; set; }
        [Column("Denomination:-200")]
        public int Denomination200 { get; set; }
        [Column("Denomination:-500")]
        public int Denomination500 { get; set; }
        [Column("Denomination:-1000")]
        public int Denomination1000 { get; set; }
        [Column("Account-Number")]
        [StringLength(50)]
        [Unicode(false)]
        public string AccountNumber { get; set; }
        [Column("Account-Name")]
        [StringLength(50)]
        [Unicode(false)]
        public string AccountName { get; set; }
        [Column("Reference-Account-Number")]
        [StringLength(50)]
        [Unicode(false)]
        public string ReferenceAccountNumber { get; set; }
        [Column("Reference-Account-Name")]
        [StringLength(50)]
        [Unicode(false)]
        public string ReferenceAccountName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Narration { get; set; }
        [Column("Depositor-Name")]
        [StringLength(50)]
        [Unicode(false)]
        public string DepositorName { get; set; }
        [Column("ID-Number")]
        [StringLength(50)]
        [Unicode(false)]
        public string IdNumber { get; set; }
        [Column("Phone-Number")]
        [StringLength(50)]
        [Unicode(false)]
        public string PhoneNumber { get; set; }
        public int Result { get; set; }
        [Column("Error-Code")]
        public int ErrorCode { get; set; }
        [Column("Error-Message")]
        [StringLength(255)]
        [Unicode(false)]
        public string ErrorMessage { get; set; }
        [Column("CB-Status")]
        [StringLength(16)]
        [Unicode(false)]
        public string CbStatus { get; set; }
        [Column("Jam-Detected")]
        public bool JamDetected { get; set; }
        [Column("Random-Number")]
        public int? RandomNumber { get; set; }
        [Column("Transaction-ID")]
        public Guid TransactionId { get; set; }
        [Column("CIT-ID")]
        public Guid? CitId { get; set; }
        [Column("Device-ID")]
        public Guid DeviceId { get; set; }
    }
}