// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Setup.Models
{
    [Keyless]
    public partial class ViewConfig
    {
        [Required]
        [Column("config_id")]
        [StringLength(50)]
        public string ConfigId { get; set; }
        [Required]
        [Column("value")]
        public string Value { get; set; }
    }
}