// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    /// <summary>
    /// contains a crash report
    /// </summary>
    [Table("CrashEvent", Schema = "exp")]
    [Index("DeviceId", Name = "idevice_id_exp_CrashEvent_7BCB8F5E")]
    public partial class CrashEvent
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("device_id")]
        public Guid DeviceId { get; set; }
        [Column("datetime")]
        public DateTime Datetime { get; set; }
        [Column("date_detected")]
        public DateTime DateDetected { get; set; }
        [Column("content")]
        public string Content { get; set; } = null!;
        [Column("machine_name")]
        [StringLength(50)]
        public string MachineName { get; set; } = null!;
    }
}