// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("Currency")]
    public partial class Currency
    {
        public Currency()
        {
            CITDenominations = new HashSet<CITDenomination>();
            CurrencyListCurrencies = new HashSet<CurrencyListCurrency>();
            CurrencyLists = new HashSet<CurrencyList>();
            DeviceCitsuspenseAccounts = new HashSet<DeviceCitsuspenseAccount>();
            DeviceSuspenseAccounts = new HashSet<DeviceSuspenseAccount>();
            TransactionLimitListItems = new HashSet<TransactionLimitListItem>();
            TransactionTypeListItems = new HashSet<TransactionTypeListItem>();
            Transactions = new HashSet<Transaction>();
        }

        [Key]
        [Column("code")]
        [StringLength(3)]
        [Unicode(false)]
        public string Code { get; set; } = null!;
        [Column("name")]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; } = null!;
        [Column("minor")]
        public int Minor { get; set; }
        [Column("flag")]
        [StringLength(2)]
        [Unicode(false)]
        public string Flag { get; set; } = null!;
        [Column("enabled")]
        public bool Enabled { get; set; }
        [Column("ISO_3_Numeric_Code")]
        [StringLength(3)]
        [Unicode(false)]
        public string? Iso3NumericCode { get; set; }

        [InverseProperty("Currency")]
        public virtual ICollection<CITDenomination> CITDenominations { get; set; }
        [InverseProperty("CurrencyItemNavigation")]
        public virtual ICollection<CurrencyListCurrency> CurrencyListCurrencies { get; set; }
        [InverseProperty("DefaultCurrencyNavigation")]
        public virtual ICollection<CurrencyList> CurrencyLists { get; set; }
        [InverseProperty("CurrencyCodeNavigation")]
        public virtual ICollection<DeviceCitsuspenseAccount> DeviceCitsuspenseAccounts { get; set; }
        [InverseProperty("CurrencyCodeNavigation")]
        public virtual ICollection<DeviceSuspenseAccount> DeviceSuspenseAccounts { get; set; }
        [InverseProperty("CurrencyCodeNavigation")]
        public virtual ICollection<TransactionLimitListItem> TransactionLimitListItems { get; set; }
        [InverseProperty("DefaultAccountCurrencyNavigation")]
        public virtual ICollection<TransactionTypeListItem> TransactionTypeListItems { get; set; }
        [InverseProperty("TxCurrencyNavigation")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}