// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("DeviceSuspenseAccount")]
    [Index("DeviceId", "CurrencyCode", Name = "UX_Device_SuspenseAccount", IsUnique = true)]
    [Index("CurrencyCode", Name = "icurrency_code_DeviceSuspenseAccount")]
    [Index("DeviceId", Name = "idevice_id_DeviceSuspenseAccount")]
    public partial class DeviceSuspenseAccount
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("device_id")]
        public Guid DeviceId { get; set; }
        [Column("currency_code")]
        [StringLength(3)]
        [Unicode(false)]
        public string CurrencyCode { get; set; } = null!;
        [Column("account_number")]
        [StringLength(50)]
        public string AccountNumber { get; set; } = null!;
        [Column("account_name")]
        [StringLength(100)]
        public string? AccountName { get; set; }
        [Column("enabled")]
        public bool Enabled { get; set; }
        [Column("account")]
        public Guid? Account { get; set; }

        [ForeignKey("CurrencyCode")]
        [InverseProperty("DeviceSuspenseAccounts")]
        public virtual Currency CurrencyCodeNavigation { get; set; } = null!;
        [ForeignKey("DeviceId")]
        [InverseProperty("DeviceSuspenseAccounts")]
        public virtual Device Device { get; set; } = null!;
    }
}