// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("Device")]
    [Index("GUIScreenList", Name = "iGUIScreen_list_DeviceList")]
    [Index("BranchId", Name = "ibranch_id_DeviceList")]
    [Index("ConfigGroup", Name = "iconfig_group_DeviceList")]
    [Index("CurrencyList", Name = "icurrency_list_DeviceList")]
    [Index("LanguageList", Name = "ilanguage_list_Device")]
    [Index("TransactionTypeList", Name = "itransaction_type_list_DeviceList")]
    [Index("TypeId", Name = "itype_id_DeviceList")]
    [Index("UserGroup", Name = "iuser_group_DeviceList")]
    public partial class Device
    {
        public Device()
        {
            Cits = new HashSet<Cit>();
            DepositorSessions = new HashSet<DepositorSession>();
            DeviceCitsuspenseAccounts = new HashSet<DeviceCitsuspenseAccount>();
            DeviceLocks = new HashSet<DeviceLock>();
            DeviceLogins = new HashSet<DeviceLogin>();
            DevicePrinters = new HashSet<DevicePrinter>();
            DeviceSuspenseAccounts = new HashSet<DeviceSuspenseAccount>();
            Transactions = new HashSet<Transaction>();
        }

        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("device_number")]
        [StringLength(50)]
        public string DeviceNumber { get; set; } = null!;
        [Column("device_location")]
        [StringLength(50)]
        public string DeviceLocation { get; set; } = null!;
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; } = null!;
        [Column("machine_name")]
        [StringLength(128)]
        public string? MachineName { get; set; }
        [Column("branch_id")]
        public Guid BranchId { get; set; }
        [Column("description")]
        [StringLength(255)]
        public string? Description { get; set; }
        [Column("type_id")]
        public int TypeId { get; set; }
        [Column("enabled")]
        public bool Enabled { get; set; }
        [Column("config_group")]
        public int ConfigGroup { get; set; }
        [Column("user_group")]
        public int? UserGroup { get; set; }
        [Column("GUIScreen_list")]
        public int GUIScreenList { get; set; }
        [Column("language_list")]
        public int? LanguageList { get; set; }
        [Column("currency_list")]
        public int CurrencyList { get; set; }
        [Column("transaction_type_list")]
        public int TransactionTypeList { get; set; }
        [Column("login_cycles")]
        public int LoginCycles { get; set; }
        [Column("login_attempts")]
        public int LoginAttempts { get; set; }
        [Column("mac_address")]
        [StringLength(17)]
        [Unicode(false)]
        public string? MacAddress { get; set; }
        [Column("app_id")]
        public Guid AppId { get; set; }
        [Column("app_key")]
        [MaxLength(32)]
        public byte[] AppKey { get; set; } = null!;

        [ForeignKey("BranchId")]
        [InverseProperty("Devices")]
        public virtual Branch Branch { get; set; } = null!;
        [ForeignKey("ConfigGroup")]
        [InverseProperty("Devices")]
        public virtual ConfigGroup ConfigGroupNavigation { get; set; } = null!;
        [ForeignKey("CurrencyList")]
        [InverseProperty("Devices")]
        public virtual CurrencyList CurrencyListNavigation { get; set; } = null!;
        [ForeignKey("GUIScreenList")]
        [InverseProperty("Devices")]
        public virtual GUIScreenList GUIScreenListNavigation { get; set; } = null!;
        [ForeignKey("LanguageList")]
        [InverseProperty("Devices")]
        public virtual LanguageList? LanguageListNavigation { get; set; }
        [ForeignKey("TransactionTypeList")]
        [InverseProperty("Devices")]
        public virtual TransactionTypeList TransactionTypeListNavigation { get; set; } = null!;
        [ForeignKey("TypeId")]
        [InverseProperty("Devices")]
        public virtual DeviceType Type { get; set; } = null!;
        [ForeignKey("UserGroup")]
        [InverseProperty("Devices")]
        public virtual UserGroup? UserGroupNavigation { get; set; }
        [InverseProperty("Device")]
        public virtual ICollection<Cit> Cits { get; set; }
        [InverseProperty("Device")]
        public virtual ICollection<DepositorSession> DepositorSessions { get; set; }
        [InverseProperty("Device")]
        public virtual ICollection<DeviceCitsuspenseAccount> DeviceCitsuspenseAccounts { get; set; }
        [InverseProperty("Device")]
        public virtual ICollection<DeviceLock> DeviceLocks { get; set; }
        [InverseProperty("Device")]
        public virtual ICollection<DeviceLogin> DeviceLogins { get; set; }
        [InverseProperty("Device")]
        public virtual ICollection<DevicePrinter> DevicePrinters { get; set; }
        [InverseProperty("Device")]
        public virtual ICollection<DeviceSuspenseAccount> DeviceSuspenseAccounts { get; set; }
        [InverseProperty("Device")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}