// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("LanguageList")]
    [Index("DefaultLanguage", Name = "idefault_language_LanguageList")]
    public partial class LanguageList
    {
        public LanguageList()
        {
            Devices = new HashSet<Device>();
            LanguageListLanguages = new HashSet<LanguageListLanguage>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; } = null!;
        [Column("description")]
        [StringLength(100)]
        public string? Description { get; set; }
        [Required]
        [Column("enabled")]
        public bool? Enabled { get; set; }
        [Column("default_language")]
        [StringLength(5)]
        [Unicode(false)]
        public string DefaultLanguage { get; set; } = null!;

        [ForeignKey("DefaultLanguage")]
        [InverseProperty("LanguageLists")]
        public virtual Language DefaultLanguageNavigation { get; set; } = null!;
        [InverseProperty("LanguageListNavigation")]
        public virtual ICollection<Device> Devices { get; set; }
        [InverseProperty("LanguageListNavigation")]
        public virtual ICollection<LanguageListLanguage> LanguageListLanguages { get; set; }
    }
}