// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("sysTextTranslation", Schema = "xlns")]
    [Index("LanguageCode", "SysTextItemId", Name = "UX_Translation_Language_Pair", IsUnique = true)]
    [Index("LanguageCode", Name = "iLanguageCode_xlns_sysTextTranslation_03BB080F")]
    [Index("SysTextItemId", Name = "iSysTextItemID_xlns_sysTextTranslation_7FDC4652")]
    public partial class SysTextTranslation
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("SysTextItemID")]
        public Guid SysTextItemId { get; set; }
        [StringLength(5)]
        [Unicode(false)]
        public string LanguageCode { get; set; } = null!;
        public string TranslationSysText { get; set; } = null!;

        [ForeignKey("LanguageCode")]
        [InverseProperty("SysTextTranslations")]
        public virtual Language LanguageCodeNavigation { get; set; } = null!;
        [ForeignKey("SysTextItemId")]
        [InverseProperty("SysTextTranslations")]
        public virtual SysTextItem SysTextItem { get; set; } = null!;
    }
}