// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("TransactionText")]
    [Index("TxItem", Name = "UX_TransactionText_tx_item", IsUnique = true)]
    [Index("FundsSourceCaption", Name = "iFundsSource_caption_TransactionText")]
    [Index("AccountNameCaption", Name = "iaccount_name_caption_TransactionText")]
    [Index("AccountNumberCaption", Name = "iaccount_number_caption_TransactionText")]
    [Index("AliasAccountNameCaption", Name = "ialias_account_name_caption_TransactionText")]
    [Index("AliasAccountNumberCaption", Name = "ialias_account_number_caption_TransactionText")]
    [Index("DepositorNameCaption", Name = "idepositor_name_caption_TransactionText")]
    [Index("Disclaimer", Name = "idisclaimer_TransactionText")]
    [Index("FullInstructions", Name = "ifull_instructions_TransactionText")]
    [Index("IdNumberCaption", Name = "iid_number_caption_TransactionText")]
    [Index("ListItemCaption", Name = "ilistItem_caption_TransactionText")]
    [Index("NarrationCaption", Name = "inarration_caption_TransactionText")]
    [Index("PhoneNumberCaption", Name = "iphone_number_caption_TransactionText")]
    [Index("ReceiptTemplate", Name = "ireceipt_template_TransactionText")]
    [Index("ReferenceAccountNameCaption", Name = "ireference_account_name_caption_TransactionText")]
    [Index("ReferenceAccountNumberCaption", Name = "ireference_account_number_caption_TransactionText")]
    [Index("Terms", Name = "iterms_TransactionText")]
    [Index("TxItem", Name = "itx_item_TransactionText")]
    public partial class TransactionText
    {
        public TransactionText()
        {
            TransactionTypeListItems = new HashSet<TransactionTypeListItem>();
        }

        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("tx_item")]
        public int TxItem { get; set; }
        [Column("disclaimer")]
        public Guid? Disclaimer { get; set; }
        [Column("terms")]
        public Guid? Terms { get; set; }
        [Column("full_instructions")]
        public Guid? FullInstructions { get; set; }
        [Column("listItem_caption")]
        public Guid? ListItemCaption { get; set; }
        [Column("account_number_caption")]
        public Guid? AccountNumberCaption { get; set; }
        [Column("account_name_caption")]
        public Guid? AccountNameCaption { get; set; }
        [Column("reference_account_number_caption")]
        public Guid? ReferenceAccountNumberCaption { get; set; }
        [Column("reference_account_name_caption")]
        public Guid? ReferenceAccountNameCaption { get; set; }
        [Column("narration_caption")]
        public Guid? NarrationCaption { get; set; }
        [Column("alias_account_number_caption")]
        public Guid? AliasAccountNumberCaption { get; set; }
        [Column("alias_account_name_caption")]
        public Guid? AliasAccountNameCaption { get; set; }
        [Column("depositor_name_caption")]
        public Guid? DepositorNameCaption { get; set; }
        [Column("phone_number_caption")]
        public Guid? PhoneNumberCaption { get; set; }
        [Column("id_number_caption")]
        public Guid? IdNumberCaption { get; set; }
        [Column("receipt_template")]
        public Guid? ReceiptTemplate { get; set; }
        [Column("FundsSource_caption")]
        public Guid? FundsSourceCaption { get; set; }

        [ForeignKey("AccountNameCaption")]
        [InverseProperty("TransactionTextAccountNameCaptionNavigations")]
        public virtual TextItem? AccountNameCaptionNavigation { get; set; }
        [ForeignKey("AccountNumberCaption")]
        [InverseProperty("TransactionTextAccountNumberCaptionNavigations")]
        public virtual TextItem? AccountNumberCaptionNavigation { get; set; }
        [ForeignKey("AliasAccountNameCaption")]
        [InverseProperty("TransactionTextAliasAccountNameCaptionNavigations")]
        public virtual TextItem? AliasAccountNameCaptionNavigation { get; set; }
        [ForeignKey("AliasAccountNumberCaption")]
        [InverseProperty("TransactionTextAliasAccountNumberCaptionNavigations")]
        public virtual TextItem? AliasAccountNumberCaptionNavigation { get; set; }
        [ForeignKey("DepositorNameCaption")]
        [InverseProperty("TransactionTextDepositorNameCaptionNavigations")]
        public virtual TextItem? DepositorNameCaptionNavigation { get; set; }
        [ForeignKey("Disclaimer")]
        [InverseProperty("TransactionTextDisclaimerNavigations")]
        public virtual TextItem? DisclaimerNavigation { get; set; }
        [ForeignKey("FullInstructions")]
        [InverseProperty("TransactionTextFullInstructionsNavigations")]
        public virtual TextItem? FullInstructionsNavigation { get; set; }
        [ForeignKey("FundsSourceCaption")]
        [InverseProperty("TransactionTextFundsSourceCaptionNavigations")]
        public virtual TextItem? FundsSourceCaptionNavigation { get; set; }
        [ForeignKey("IdNumberCaption")]
        [InverseProperty("TransactionTextIdNumberCaptionNavigations")]
        public virtual TextItem? IdNumberCaptionNavigation { get; set; }
        [ForeignKey("ListItemCaption")]
        [InverseProperty("TransactionTextListItemCaptionNavigations")]
        public virtual TextItem? ListItemCaptionNavigation { get; set; }
        [ForeignKey("NarrationCaption")]
        [InverseProperty("TransactionTextNarrationCaptionNavigations")]
        public virtual TextItem? NarrationCaptionNavigation { get; set; }
        [ForeignKey("PhoneNumberCaption")]
        [InverseProperty("TransactionTextPhoneNumberCaptionNavigations")]
        public virtual TextItem? PhoneNumberCaptionNavigation { get; set; }
        [ForeignKey("ReceiptTemplate")]
        [InverseProperty("TransactionTextReceiptTemplateNavigations")]
        public virtual TextItem? ReceiptTemplateNavigation { get; set; }
        [ForeignKey("ReferenceAccountNameCaption")]
        [InverseProperty("TransactionTextReferenceAccountNameCaptionNavigations")]
        public virtual TextItem? ReferenceAccountNameCaptionNavigation { get; set; }
        [ForeignKey("ReferenceAccountNumberCaption")]
        [InverseProperty("TransactionTextReferenceAccountNumberCaptionNavigations")]
        public virtual TextItem? ReferenceAccountNumberCaptionNavigation { get; set; }
        [ForeignKey("Terms")]
        [InverseProperty("TransactionTextTermsNavigations")]
        public virtual TextItem? TermsNavigation { get; set; }
        [ForeignKey("TxItem")]
        [InverseProperty("TransactionText")]
        public virtual TransactionTypeListItem TxItemNavigation { get; set; } = null!;
        [InverseProperty("TxTextNavigation")]
        public virtual ICollection<TransactionTypeListItem> TransactionTypeListItems { get; set; }
    }
}