// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("Transaction")]
    [Index("CitId", Name = "iCIT_id_Transaction")]
    [Index("DeviceId", Name = "idevice_Transaction")]
    [Index("SessionId", Name = "isession_id_Transaction")]
    [Index("TxCurrency", Name = "itx_currency_Transaction")]
    [Index("TxType", Name = "itx_type_Transaction")]
    public partial class Transaction
    {
        public Transaction()
        {
            DenominationDetails = new HashSet<DenominationDetail>();
            EscrowJams = new HashSet<EscrowJam>();
            Printouts = new HashSet<Printout>();
        }

        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("tx_type")]
        public int? TxType { get; set; }
        [Column("session_id")]
        public Guid SessionId { get; set; }
        [Column("tx_random_number")]
        public int? TxRandomNumber { get; set; }
        [Column("device_id")]
        public Guid DeviceId { get; set; }
        [Column("tx_start_date")]
        public DateTime TxStartDate { get; set; }
        [Column("tx_end_date")]
        public DateTime? TxEndDate { get; set; }
        [Column("tx_completed")]
        public bool TxCompleted { get; set; }
        [Column("tx_currency")]
        [StringLength(3)]
        [Unicode(false)]
        public string? TxCurrency { get; set; }
        [Column("tx_amount")]
        public long? TxAmount { get; set; }
        [Column("tx_account_number")]
        [StringLength(50)]
        public string? TxAccountNumber { get; set; }
        [Column("cb_account_name")]
        [StringLength(100)]
        public string? CbAccountName { get; set; }
        [Column("tx_ref_account")]
        [StringLength(50)]
        public string? TxRefAccount { get; set; }
        [Column("cb_ref_account_name")]
        [StringLength(100)]
        public string? CbRefAccountName { get; set; }
        [Column("tx_narration")]
        [StringLength(50)]
        public string? TxNarration { get; set; }
        [Column("tx_depositor_name")]
        [StringLength(50)]
        public string? TxDepositorName { get; set; }
        [Column("tx_id_number")]
        [StringLength(50)]
        public string? TxIdNumber { get; set; }
        [Column("tx_phone")]
        [StringLength(50)]
        public string? TxPhone { get; set; }
        [Column("funds_source")]
        [StringLength(255)]
        public string? FundsSource { get; set; }
        [Column("tx_result")]
        public int TxResult { get; set; }
        [Column("tx_error_code")]
        public int TxErrorCode { get; set; }
        [Column("tx_error_message")]
        [StringLength(255)]
        public string? TxErrorMessage { get; set; }
        [Column("cb_tx_number")]
        [StringLength(50)]
        public string? CbTxNumber { get; set; }
        [Column("cb_date")]
        public DateTime? CbDate { get; set; }
        [Column("cb_tx_status")]
        [StringLength(50)]
        public string? CbTxStatus { get; set; }
        [Column("cb_status_detail")]
        public string? CbStatusDetail { get; set; }
        [Column("notes_rejected")]
        public bool NotesRejected { get; set; }
        [Column("jam_detected")]
        public bool JamDetected { get; set; }
        [Column("CIT_id")]
        public Guid? CitId { get; set; }
        [Column("escrow_jam")]
        public bool EscrowJam { get; set; }
        [Column("tx_suspense_account")]
        [StringLength(50)]
        public string? TxSuspenseAccount { get; set; }
        [Column("init_user")]
        public Guid? InitUser { get; set; }
        [Column("auth_user")]
        public Guid? AuthUser { get; set; }

        [ForeignKey("AuthUser")]
        [InverseProperty("TransactionAuthUserNavigations")]
        public virtual ApplicationUser? AuthUserNavigation { get; set; }
        [ForeignKey("CitId")]
        [InverseProperty("Transactions")]
        public virtual Cit? Cit { get; set; }
        [ForeignKey("DeviceId")]
        [InverseProperty("Transactions")]
        public virtual Device Device { get; set; } = null!;
        [ForeignKey("InitUser")]
        [InverseProperty("TransactionInitUserNavigations")]
        public virtual ApplicationUser? InitUserNavigation { get; set; }
        [ForeignKey("SessionId")]
        [InverseProperty("Transactions")]
        public virtual DepositorSession Session { get; set; } = null!;
        [ForeignKey("TxCurrency")]
        [InverseProperty("Transactions")]
        public virtual Currency? TxCurrencyNavigation { get; set; }
        [ForeignKey("TxType")]
        [InverseProperty("Transactions")]
        public virtual TransactionTypeListItem? TxTypeNavigation { get; set; }
        [InverseProperty("Tx")]
        public virtual ICollection<DenominationDetail> DenominationDetails { get; set; }
        [InverseProperty("Transaction")]
        public virtual ICollection<EscrowJam> EscrowJams { get; set; }
        [InverseProperty("Tx")]
        public virtual ICollection<Printout> Printouts { get; set; }
    }
}