// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("ValidationItemValue")]
    [Index("ValidationItemId", "Order", Name = "UX_ValidationItemValue", IsUnique = true)]
    [Index("ValidationItemId", Name = "ivalidation_item_id_ValidationItemValue")]
    public partial class ValidationItemValue
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("validation_item_id")]
        public Guid ValidationItemId { get; set; }
        [Column("value")]
        [StringLength(255)]
        public string Value { get; set; } = null!;
        [Column("order")]
        public int Order { get; set; }

        [ForeignKey("ValidationItemId")]
        [InverseProperty("ValidationItemValues")]
        public virtual ValidationItem ValidationItem { get; set; } = null!;
    }
}