// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("ValidationType")]
    public partial class ValidationType
    {
        public ValidationType()
        {
            ValidationItems = new HashSet<ValidationItem>();
        }

        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; } = null!;
        [Column("description")]
        [StringLength(255)]
        public string? Description { get; set; }
        [Column("enabled")]
        public bool Enabled { get; set; }

        [InverseProperty("Type")]
        public virtual ICollection<ValidationItem> ValidationItems { get; set; }
    }
}