// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cashmere.Finacle.Integration.CQRS.DataAccessLayer.Models
{
    /// <summary>
    /// Currency enumeration
    /// </summary>
    [Table("Currency")]
    public partial class Currency
    {
        public Currency()
        {
        }

        /// <summary>
        /// ISO 4217 Three Character Currency Code
        /// </summary>
        [Key]
        [Column("code")]
        [StringLength(3)]
        [Unicode(false)]
        public string Code { get; set; }
        /// <summary>
        /// Name of the currency
        /// </summary>
        [Required]
        [Column("name")]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        /// <summary>
        /// Expresses the relationship between a major currency unit and its corresponding minor currency unit. This mechanism is called the currency &quot;exponent&quot; and assumes a base of 10. Will be used with converters in the GUI
        /// </summary>
        [Column("minor")]
        public int Minor { get; set; }
        /// <summary>
        /// two character country code for the national flag to display for the language
        /// </summary>
        [Column("flag")]
        [StringLength(255)]
        public string Flag { get; set; }
        /// <summary>
        /// whether the system supports the language
        /// </summary>
        [Column("enabled")]
        public bool Enabled { get; set; }
    
        /// <summary>
        /// two character country code for the national flag to display for the language
        /// </summary>
        [Column("iso_3_numeric_code")]
        [StringLength(255)]
        public string ISO_3_Numeric_Code { get; set; }
    }
}