// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Cashmere.Finacle.Integration.CQRS.DataAccessLayer.Models
{
    [Table("Device")]
    [Index("BranchId", Name = "ibranch_id_DeviceList")]
    public partial class Device
    {
        public Device()
        {
        }

        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Required]
        [Column("device_number")]
        [StringLength(50)]
        public string DeviceNumber { get; set; }
        [Required]
        [Column("device_location")]
        [StringLength(50)]
        public string DeviceLocation { get; set; }
        [Required]
        [Column("name")]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [Column("machine_name")]
        [StringLength(128)]
        public string MachineName { get; set; }
        [Column("branch_id")]
        public Guid BranchId { get; set; }
        [Column("description")]
        [StringLength(255)]
        [Unicode(false)]
        public string Description { get; set; }
        [Column("enabled")]
        public bool Enabled { get; set; }
        /// <summary>
        /// how many cycles of failed logins have been detected. used to lock the machine in case of password guessing
        /// </summary>
        [Column("login_cycles")]
        public int LoginCycles { get; set; }
        /// <summary>
        /// how many times in a row a login attempt has failed
        /// </summary>
        [Column("login_attempts")]
        public int LoginAttempts { get; set; }
        [Required]
        [Column("username")]
        [StringLength(128)]
        [Unicode(false)]
        public string Username { get; set; }
        [Required]
        [Column("password")]
        [StringLength(128)]
        [Unicode(false)]
        public string Password { get; set; }

        [ForeignKey("BranchId")]
        //[InverseProperty("Devices")]
        public virtual Branch Branch { get; set; }
    }
}