//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSAccountDetailsServiceReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Event/Fault")]
    public partial class FaultType
    {
        
        private ResponseHeaderType faultHeaderField;
        
        private string severityField;
        
        private string exceptionIdField;
        
        private System.DateTime exceptionTimestampField;
        
        private string exceptionCodeField;
        
        private string exceptionNameField;
        
        private string exceptionDescriptionField;
        
        private string exceptionDetailsField;
        
        private FaultDetailsType faultDetailsField;
        
        private RuntimeContextType runtimeContextField;
        
        private System.Xml.XmlElement payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseHeaderType FaultHeader
        {
            get
            {
                return this.faultHeaderField;
            }
            set
            {
                this.faultHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ExceptionId
        {
            get
            {
                return this.exceptionIdField;
            }
            set
            {
                this.exceptionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ExceptionTimestamp
        {
            get
            {
                return this.exceptionTimestampField;
            }
            set
            {
                this.exceptionTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ExceptionCode
        {
            get
            {
                return this.exceptionCodeField;
            }
            set
            {
                this.exceptionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ExceptionName
        {
            get
            {
                return this.exceptionNameField;
            }
            set
            {
                this.exceptionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ExceptionDescription
        {
            get
            {
                return this.exceptionDescriptionField;
            }
            set
            {
                this.exceptionDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ExceptionDetails
        {
            get
            {
                return this.exceptionDetailsField;
            }
            set
            {
                this.exceptionDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public FaultDetailsType FaultDetails
        {
            get
            {
                return this.faultDetailsField;
            }
            set
            {
                this.faultDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Internal/RuntimeContext", Order=9)]
        public RuntimeContextType RuntimeContext
        {
            get
            {
                return this.runtimeContextField;
            }
            set
            {
                this.runtimeContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Common", Order=10)]
        public System.Xml.XmlElement Payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Message/MessageHeader")]
    public partial class ResponseHeaderType
    {
        
        private string correlationIDField;
        
        private long elapsedTimeField;
        
        private bool elapsedTimeFieldSpecified;
        
        private string messageIDField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        private string statusDescriptionKeyField;
        
        private StatusMessagesType statusMessagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Common", Order=0)]
        public string CorrelationID
        {
            get
            {
                return this.correlationIDField;
            }
            set
            {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long ElapsedTime
        {
            get
            {
                return this.elapsedTimeField;
            }
            set
            {
                this.elapsedTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ElapsedTimeSpecified
        {
            get
            {
                return this.elapsedTimeFieldSpecified;
            }
            set
            {
                this.elapsedTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MessageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string StatusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StatusDescriptionKey
        {
            get
            {
                return this.statusDescriptionKeyField;
            }
            set
            {
                this.statusDescriptionKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public StatusMessagesType StatusMessages
        {
            get
            {
                return this.statusMessagesField;
            }
            set
            {
                this.statusMessagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Message/MessageHeader")]
    public partial class StatusMessagesType
    {
        
        private string applicationIDField;
        
        private string messageCodeField;
        
        private string messageDescriptionField;
        
        private string messageTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ApplicationID
        {
            get
            {
                return this.applicationIDField;
            }
            set
            {
                this.applicationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MessageCode
        {
            get
            {
                return this.messageCodeField;
            }
            set
            {
                this.messageCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MessageDescription
        {
            get
            {
                return this.messageDescriptionField;
            }
            set
            {
                this.messageDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MessageType
        {
            get
            {
                return this.messageTypeField;
            }
            set
            {
                this.messageTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Internal/RuntimeContext")]
    public partial class RuntimeContextType
    {
        
        private string serviceNameField;
        
        private string applicationField;
        
        private string applicationVersionField;
        
        private string appNodeField;
        
        private string hostnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ApplicationVersion
        {
            get
            {
                return this.applicationVersionField;
            }
            set
            {
                this.applicationVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AppNode
        {
            get
            {
                return this.appNodeField;
            }
            set
            {
                this.appNodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Hostname
        {
            get
            {
                return this.hostnameField;
            }
            set
            {
                this.hostnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Event/Fault")]
    public partial class FaultDetailsType
    {
        
        private string activityNameField;
        
        private System.Xml.XmlElement dataField;
        
        private string msgField;
        
        private string msgCodeField;
        
        private string processStackField;
        
        private string stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ActivityName
        {
            get
            {
                return this.activityNameField;
            }
            set
            {
                this.activityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Xml.XmlElement Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Msg
        {
            get
            {
                return this.msgField;
            }
            set
            {
                this.msgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MsgCode
        {
            get
            {
                return this.msgCodeField;
            }
            set
            {
                this.msgCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ProcessStack
        {
            get
            {
                return this.processStackField;
            }
            set
            {
                this.processStackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StackTrace
        {
            get
            {
                return this.stackTraceField;
            }
            set
            {
                this.stackTraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://co-opbank.co.ke/BS/Account/BSAccountDetails.3.0")]
    public partial class AccountDetailsResponseType
    {
        
        private string accountNumberField;
        
        private string accountNameField;
        
        private string currencyCodeField;
        
        private string jointAccountField;
        
        private string productIDField;
        
        private string productContextCodeField;
        
        private string productNameField;
        
        private decimal clearedBalanceField;
        
        private bool clearedBalanceFieldSpecified;
        
        private decimal bookedBalanceField;
        
        private bool bookedBalanceFieldSpecified;
        
        private decimal blockedBalanceField;
        
        private bool blockedBalanceFieldSpecified;
        
        private decimal availableBalanceField;
        
        private bool availableBalanceFieldSpecified;
        
        private string branchNameField;
        
        private string phoneNumberField;
        
        private string customerCodeField;
        
        private string emailField;
        
        private string dormantField;
        
        private string stoppedField;
        
        private string closedField;
        
        private string accountRightsIndicatorField;
        
        private string postalAddressField;
        
        private string townField;
        
        private string openDateField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AccountName
        {
            get
            {
                return this.accountNameField;
            }
            set
            {
                this.accountNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CurrencyCode
        {
            get
            {
                return this.currencyCodeField;
            }
            set
            {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string JointAccount
        {
            get
            {
                return this.jointAccountField;
            }
            set
            {
                this.jointAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ProductID
        {
            get
            {
                return this.productIDField;
            }
            set
            {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ProductContextCode
        {
            get
            {
                return this.productContextCodeField;
            }
            set
            {
                this.productContextCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ProductName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal ClearedBalance
        {
            get
            {
                return this.clearedBalanceField;
            }
            set
            {
                this.clearedBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClearedBalanceSpecified
        {
            get
            {
                return this.clearedBalanceFieldSpecified;
            }
            set
            {
                this.clearedBalanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal BookedBalance
        {
            get
            {
                return this.bookedBalanceField;
            }
            set
            {
                this.bookedBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BookedBalanceSpecified
        {
            get
            {
                return this.bookedBalanceFieldSpecified;
            }
            set
            {
                this.bookedBalanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal BlockedBalance
        {
            get
            {
                return this.blockedBalanceField;
            }
            set
            {
                this.blockedBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BlockedBalanceSpecified
        {
            get
            {
                return this.blockedBalanceFieldSpecified;
            }
            set
            {
                this.blockedBalanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal AvailableBalance
        {
            get
            {
                return this.availableBalanceField;
            }
            set
            {
                this.availableBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AvailableBalanceSpecified
        {
            get
            {
                return this.availableBalanceFieldSpecified;
            }
            set
            {
                this.availableBalanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string BranchName
        {
            get
            {
                return this.branchNameField;
            }
            set
            {
                this.branchNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CustomerCode
        {
            get
            {
                return this.customerCodeField;
            }
            set
            {
                this.customerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Dormant
        {
            get
            {
                return this.dormantField;
            }
            set
            {
                this.dormantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Stopped
        {
            get
            {
                return this.stoppedField;
            }
            set
            {
                this.stoppedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Closed
        {
            get
            {
                return this.closedField;
            }
            set
            {
                this.closedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string AccountRightsIndicator
        {
            get
            {
                return this.accountRightsIndicatorField;
            }
            set
            {
                this.accountRightsIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string PostalAddress
        {
            get
            {
                return this.postalAddressField;
            }
            set
            {
                this.postalAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Town
        {
            get
            {
                return this.townField;
            }
            set
            {
                this.townField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string OpenDate
        {
            get
            {
                return this.openDateField;
            }
            set
            {
                this.openDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://co-opbank.co.ke/BS/Account/BSAccountDetails.3.0")]
    public partial class AccountDetailsRequestType
    {
        
        private string accountNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn://co-opbank.co.ke/BS/Account/AccountDetails/Get/3.0", ConfigurationName="BSAccountDetailsServiceReference.BSGetAccountDetails")]
    public interface BSGetAccountDetails
    {
        
        // CODEGEN: Generating message contract since the operation GetAccountDetails is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetAccountDetails", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(BSAccountDetailsServiceReference.FaultType), Action="GetAccountDetails", Name="Fault", Namespace="urn://co-opbank.co.ke/CommonServices/Data/Event/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BSAccountDetailsServiceReference.operationOutput GetAccountDetails(BSAccountDetailsServiceReference.operationInput request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetAccountDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<BSAccountDetailsServiceReference.operationOutput> GetAccountDetailsAsync(BSAccountDetailsServiceReference.operationInput request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Message/MessageHeader")]
    public partial class RequestHeaderType
    {
        
        private System.DateTime creationTimestampField;
        
        private bool creationTimestampFieldSpecified;
        
        private string correlationIDField;
        
        private string faultTOField;
        
        private string messageIDField;
        
        private string replyTOField;
        
        private CredentialsType credentialsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Common", Order=0)]
        public System.DateTime CreationTimestamp
        {
            get
            {
                return this.creationTimestampField;
            }
            set
            {
                this.creationTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreationTimestampSpecified
        {
            get
            {
                return this.creationTimestampFieldSpecified;
            }
            set
            {
                this.creationTimestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Common", Order=1)]
        public string CorrelationID
        {
            get
            {
                return this.correlationIDField;
            }
            set
            {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FaultTO
        {
            get
            {
                return this.faultTOField;
            }
            set
            {
                this.faultTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MessageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ReplyTO
        {
            get
            {
                return this.replyTOField;
            }
            set
            {
                this.replyTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public CredentialsType Credentials
        {
            get
            {
                return this.credentialsField;
            }
            set
            {
                this.credentialsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Message/MessageHeader")]
    public partial class CredentialsType
    {
        
        private string systemCodeField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string realmField;
        
        private string bankIDField;
        
        public CredentialsType()
        {
            this.bankIDField = "01";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string SystemCode
        {
            get
            {
                return this.systemCodeField;
            }
            set
            {
                this.systemCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Realm
        {
            get
            {
                return this.realmField;
            }
            set
            {
                this.realmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        [System.ComponentModel.DefaultValueAttribute("01")]
        public string BankID
        {
            get
            {
                return this.bankIDField;
            }
            set
            {
                this.bankIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class operationInput
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Message/MessageHeader")]
        public BSAccountDetailsServiceReference.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://co-opbank.co.ke/BS/Account/BSAccountDetails.3.0", Order=0)]
        public BSAccountDetailsServiceReference.AccountDetailsRequestType AccountDetailsRequest;
        
        public operationInput()
        {
        }
        
        public operationInput(BSAccountDetailsServiceReference.RequestHeaderType RequestHeader, BSAccountDetailsServiceReference.AccountDetailsRequestType AccountDetailsRequest)
        {
            this.RequestHeader = RequestHeader;
            this.AccountDetailsRequest = AccountDetailsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class operationOutput
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Message/MessageHeader")]
        public BSAccountDetailsServiceReference.ResponseHeaderType ResponseHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://co-opbank.co.ke/BS/Account/BSAccountDetails.3.0", Order=0)]
        public BSAccountDetailsServiceReference.AccountDetailsResponseType AccountDetailsResponse;
        
        public operationOutput()
        {
        }
        
        public operationOutput(BSAccountDetailsServiceReference.ResponseHeaderType ResponseHeader, BSAccountDetailsServiceReference.AccountDetailsResponseType AccountDetailsResponse)
        {
            this.ResponseHeader = ResponseHeader;
            this.AccountDetailsResponse = AccountDetailsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface BSGetAccountDetailsChannel : BSAccountDetailsServiceReference.BSGetAccountDetails, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class BSGetAccountDetailsClient : System.ServiceModel.ClientBase<BSAccountDetailsServiceReference.BSGetAccountDetails>, BSAccountDetailsServiceReference.BSGetAccountDetails
    {
        
        public BSGetAccountDetailsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BSAccountDetailsServiceReference.operationOutput BSAccountDetailsServiceReference.BSGetAccountDetails.GetAccountDetails(BSAccountDetailsServiceReference.operationInput request)
        {
            return base.Channel.GetAccountDetails(request);
        }
        
        public BSAccountDetailsServiceReference.ResponseHeaderType GetAccountDetails(BSAccountDetailsServiceReference.RequestHeaderType RequestHeader, BSAccountDetailsServiceReference.AccountDetailsRequestType AccountDetailsRequest, out BSAccountDetailsServiceReference.AccountDetailsResponseType AccountDetailsResponse)
        {
            BSAccountDetailsServiceReference.operationInput inValue = new BSAccountDetailsServiceReference.operationInput();
            inValue.RequestHeader = RequestHeader;
            inValue.AccountDetailsRequest = AccountDetailsRequest;
            BSAccountDetailsServiceReference.operationOutput retVal = ((BSAccountDetailsServiceReference.BSGetAccountDetails)(this)).GetAccountDetails(inValue);
            AccountDetailsResponse = retVal.AccountDetailsResponse;
            return retVal.ResponseHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BSAccountDetailsServiceReference.operationOutput> BSAccountDetailsServiceReference.BSGetAccountDetails.GetAccountDetailsAsync(BSAccountDetailsServiceReference.operationInput request)
        {
            return base.Channel.GetAccountDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BSAccountDetailsServiceReference.operationOutput> GetAccountDetailsAsync(BSAccountDetailsServiceReference.RequestHeaderType RequestHeader, BSAccountDetailsServiceReference.AccountDetailsRequestType AccountDetailsRequest)
        {
            BSAccountDetailsServiceReference.operationInput inValue = new BSAccountDetailsServiceReference.operationInput();
            inValue.RequestHeader = RequestHeader;
            inValue.AccountDetailsRequest = AccountDetailsRequest;
            return ((BSAccountDetailsServiceReference.BSGetAccountDetails)(this)).GetAccountDetailsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
