//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSAccountFundsTransferServiceReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Event/Fault")]
    public partial class FaultType
    {
        
        private ResponseHeaderType faultHeaderField;
        
        private string severityField;
        
        private string exceptionIdField;
        
        private System.DateTime exceptionTimestampField;
        
        private string exceptionCodeField;
        
        private string exceptionNameField;
        
        private string exceptionDescriptionField;
        
        private string exceptionDetailsField;
        
        private FaultDetailsType faultDetailsField;
        
        private RuntimeContextType runtimeContextField;
        
        private System.Xml.XmlElement payloadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseHeaderType FaultHeader
        {
            get
            {
                return this.faultHeaderField;
            }
            set
            {
                this.faultHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ExceptionId
        {
            get
            {
                return this.exceptionIdField;
            }
            set
            {
                this.exceptionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ExceptionTimestamp
        {
            get
            {
                return this.exceptionTimestampField;
            }
            set
            {
                this.exceptionTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ExceptionCode
        {
            get
            {
                return this.exceptionCodeField;
            }
            set
            {
                this.exceptionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ExceptionName
        {
            get
            {
                return this.exceptionNameField;
            }
            set
            {
                this.exceptionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ExceptionDescription
        {
            get
            {
                return this.exceptionDescriptionField;
            }
            set
            {
                this.exceptionDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ExceptionDetails
        {
            get
            {
                return this.exceptionDetailsField;
            }
            set
            {
                this.exceptionDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public FaultDetailsType FaultDetails
        {
            get
            {
                return this.faultDetailsField;
            }
            set
            {
                this.faultDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Internal/RuntimeContext", Order=9)]
        public RuntimeContextType RuntimeContext
        {
            get
            {
                return this.runtimeContextField;
            }
            set
            {
                this.runtimeContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Common", Order=10)]
        public System.Xml.XmlElement Payload
        {
            get
            {
                return this.payloadField;
            }
            set
            {
                this.payloadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Message/MessageHeader")]
    public partial class ResponseHeaderType
    {
        
        private string correlationIDField;
        
        private long elapsedTimeField;
        
        private bool elapsedTimeFieldSpecified;
        
        private string messageIDField;
        
        private string statusCodeField;
        
        private string statusDescriptionField;
        
        private string statusDescriptionKeyField;
        
        private StatusMessagesType statusMessagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Common", Order=0)]
        public string CorrelationID
        {
            get
            {
                return this.correlationIDField;
            }
            set
            {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long ElapsedTime
        {
            get
            {
                return this.elapsedTimeField;
            }
            set
            {
                this.elapsedTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ElapsedTimeSpecified
        {
            get
            {
                return this.elapsedTimeFieldSpecified;
            }
            set
            {
                this.elapsedTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MessageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string StatusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StatusDescriptionKey
        {
            get
            {
                return this.statusDescriptionKeyField;
            }
            set
            {
                this.statusDescriptionKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public StatusMessagesType StatusMessages
        {
            get
            {
                return this.statusMessagesField;
            }
            set
            {
                this.statusMessagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Message/MessageHeader")]
    public partial class StatusMessagesType
    {
        
        private string applicationIDField;
        
        private string messageCodeField;
        
        private string messageDescriptionField;
        
        private string messageTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ApplicationID
        {
            get
            {
                return this.applicationIDField;
            }
            set
            {
                this.applicationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MessageCode
        {
            get
            {
                return this.messageCodeField;
            }
            set
            {
                this.messageCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MessageDescription
        {
            get
            {
                return this.messageDescriptionField;
            }
            set
            {
                this.messageDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MessageType
        {
            get
            {
                return this.messageTypeField;
            }
            set
            {
                this.messageTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Internal/RuntimeContext")]
    public partial class RuntimeContextType
    {
        
        private string serviceNameField;
        
        private string applicationField;
        
        private string applicationVersionField;
        
        private string appNodeField;
        
        private string hostnameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ServiceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ApplicationVersion
        {
            get
            {
                return this.applicationVersionField;
            }
            set
            {
                this.applicationVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AppNode
        {
            get
            {
                return this.appNodeField;
            }
            set
            {
                this.appNodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Hostname
        {
            get
            {
                return this.hostnameField;
            }
            set
            {
                this.hostnameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Event/Fault")]
    public partial class FaultDetailsType
    {
        
        private string activityNameField;
        
        private System.Xml.XmlElement dataField;
        
        private string msgField;
        
        private string msgCodeField;
        
        private string processStackField;
        
        private string stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ActivityName
        {
            get
            {
                return this.activityNameField;
            }
            set
            {
                this.activityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Xml.XmlElement Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Msg
        {
            get
            {
                return this.msgField;
            }
            set
            {
                this.msgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MsgCode
        {
            get
            {
                return this.msgCodeField;
            }
            set
            {
                this.msgCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ProcessStack
        {
            get
            {
                return this.processStackField;
            }
            set
            {
                this.processStackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string StackTrace
        {
            get
            {
                return this.stackTraceField;
            }
            set
            {
                this.stackTraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://co-opbank.co.ke/Banking/CanonicalDataModel/FundsTransfer/4.0")]
    public partial class FundsTransferType
    {
        
        private string messageReferenceField;
        
        private string systemCodeField;
        
        private string transactionDatetimeField;
        
        private System.DateTime valueDateField;
        
        private bool valueDateFieldSpecified;
        
        private string transactionIDField;
        
        private string transactionTypeField;
        
        private string transactionSubTypeField;
        
        private FundsTransferTypeTransactionItem[] transactionItemField;
        
        private FundsTransferTypeCharge[] transactionChargesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MessageReference
        {
            get
            {
                return this.messageReferenceField;
            }
            set
            {
                this.messageReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SystemCode
        {
            get
            {
                return this.systemCodeField;
            }
            set
            {
                this.systemCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransactionDatetime
        {
            get
            {
                return this.transactionDatetimeField;
            }
            set
            {
                this.transactionDatetimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ValueDate
        {
            get
            {
                return this.valueDateField;
            }
            set
            {
                this.valueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueDateSpecified
        {
            get
            {
                return this.valueDateFieldSpecified;
            }
            set
            {
                this.valueDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TransactionID
        {
            get
            {
                return this.transactionIDField;
            }
            set
            {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TransactionType
        {
            get
            {
                return this.transactionTypeField;
            }
            set
            {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TransactionSubType
        {
            get
            {
                return this.transactionSubTypeField;
            }
            set
            {
                this.transactionSubTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TransactionItem", Order=7)]
        public FundsTransferTypeTransactionItem[] TransactionItem
        {
            get
            {
                return this.transactionItemField;
            }
            set
            {
                this.transactionItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Charge", IsNullable=false)]
        public FundsTransferTypeCharge[] TransactionCharges
        {
            get
            {
                return this.transactionChargesField;
            }
            set
            {
                this.transactionChargesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://co-opbank.co.ke/Banking/CanonicalDataModel/FundsTransfer/4.0")]
    public partial class FundsTransferTypeTransactionItem
    {
        
        private string transactionReferenceField;
        
        private string transactionItemKeyField;
        
        private string accountNumberField;
        
        private string debitCreditFlagField;
        
        private decimal transactionAmountField;
        
        private bool transactionAmountFieldSpecified;
        
        private string transactionCurrencyField;
        
        private string narrativeField;
        
        private string sourceBranchField;
        
        private string transactionCodeField;
        
        private string availableBalanceField;
        
        private string bookedBalanceField;
        
        private string chequeOrDraftNumberField;
        
        private string rateCodeField;
        
        private decimal exchangeRateField;
        
        private bool exchangeRateFieldSpecified;
        
        private string temporaryODRequiredField;
        
        private FundsTransferTypeTransactionItemTemporaryODDetails temporaryODDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TransactionReference
        {
            get
            {
                return this.transactionReferenceField;
            }
            set
            {
                this.transactionReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransactionItemKey
        {
            get
            {
                return this.transactionItemKeyField;
            }
            set
            {
                this.transactionItemKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DebitCreditFlag
        {
            get
            {
                return this.debitCreditFlagField;
            }
            set
            {
                this.debitCreditFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal TransactionAmount
        {
            get
            {
                return this.transactionAmountField;
            }
            set
            {
                this.transactionAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransactionAmountSpecified
        {
            get
            {
                return this.transactionAmountFieldSpecified;
            }
            set
            {
                this.transactionAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TransactionCurrency
        {
            get
            {
                return this.transactionCurrencyField;
            }
            set
            {
                this.transactionCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Narrative
        {
            get
            {
                return this.narrativeField;
            }
            set
            {
                this.narrativeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SourceBranch
        {
            get
            {
                return this.sourceBranchField;
            }
            set
            {
                this.sourceBranchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TransactionCode
        {
            get
            {
                return this.transactionCodeField;
            }
            set
            {
                this.transactionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string AvailableBalance
        {
            get
            {
                return this.availableBalanceField;
            }
            set
            {
                this.availableBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string BookedBalance
        {
            get
            {
                return this.bookedBalanceField;
            }
            set
            {
                this.bookedBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ChequeOrDraftNumber
        {
            get
            {
                return this.chequeOrDraftNumberField;
            }
            set
            {
                this.chequeOrDraftNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string RateCode
        {
            get
            {
                return this.rateCodeField;
            }
            set
            {
                this.rateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal ExchangeRate
        {
            get
            {
                return this.exchangeRateField;
            }
            set
            {
                this.exchangeRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExchangeRateSpecified
        {
            get
            {
                return this.exchangeRateFieldSpecified;
            }
            set
            {
                this.exchangeRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string TemporaryODRequired
        {
            get
            {
                return this.temporaryODRequiredField;
            }
            set
            {
                this.temporaryODRequiredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public FundsTransferTypeTransactionItemTemporaryODDetails TemporaryODDetails
        {
            get
            {
                return this.temporaryODDetailsField;
            }
            set
            {
                this.temporaryODDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://co-opbank.co.ke/Banking/CanonicalDataModel/FundsTransfer/4.0")]
    public partial class FundsTransferTypeTransactionItemTemporaryODDetails
    {
        
        private string expiryDateField;
        
        private string permittedByField;
        
        private string intLevelField;
        
        private string remarksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ExpiryDate
        {
            get
            {
                return this.expiryDateField;
            }
            set
            {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PermittedBy
        {
            get
            {
                return this.permittedByField;
            }
            set
            {
                this.permittedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IntLevel
        {
            get
            {
                return this.intLevelField;
            }
            set
            {
                this.intLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://co-opbank.co.ke/Banking/CanonicalDataModel/FundsTransfer/4.0")]
    public partial class FundsTransferTypeCharge
    {
        
        private string eventTypeField;
        
        private string eventIdField;
        
        private string chargeAccountSerialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EventType
        {
            get
            {
                return this.eventTypeField;
            }
            set
            {
                this.eventTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EventId
        {
            get
            {
                return this.eventIdField;
            }
            set
            {
                this.eventIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ChargeAccountSerial
        {
            get
            {
                return this.chargeAccountSerialField;
            }
            set
            {
                this.chargeAccountSerialField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn://co-opbank.co.ke/BS/Account/FundsTransfer/SyncPost/4.0", ConfigurationName="BSAccountFundsTransferServiceReference.BSAccount")]
    public interface BSAccount
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="Post", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(BSAccountFundsTransferServiceReference.FaultType), Action="Post", Name="Fault", Namespace="urn://co-opbank.co.ke/CommonServices/Data/Event/Fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<BSAccountFundsTransferServiceReference.PostResponse> PostAsync(BSAccountFundsTransferServiceReference.PostRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Message/MessageHeader")]
    public partial class RequestHeaderType
    {
        
        private System.DateTime creationTimestampField;
        
        private bool creationTimestampFieldSpecified;
        
        private string correlationIDField;
        
        private string faultTOField;
        
        private string messageIDField;
        
        private string replyTOField;
        
        private CredentialsType credentialsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Common", Order=0)]
        public System.DateTime CreationTimestamp
        {
            get
            {
                return this.creationTimestampField;
            }
            set
            {
                this.creationTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreationTimestampSpecified
        {
            get
            {
                return this.creationTimestampFieldSpecified;
            }
            set
            {
                this.creationTimestampFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Common", Order=1)]
        public string CorrelationID
        {
            get
            {
                return this.correlationIDField;
            }
            set
            {
                this.correlationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FaultTO
        {
            get
            {
                return this.faultTOField;
            }
            set
            {
                this.faultTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MessageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ReplyTO
        {
            get
            {
                return this.replyTOField;
            }
            set
            {
                this.replyTOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public CredentialsType Credentials
        {
            get
            {
                return this.credentialsField;
            }
            set
            {
                this.credentialsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Message/MessageHeader")]
    public partial class CredentialsType
    {
        
        private string systemCodeField;
        
        private string usernameField;
        
        private string passwordField;
        
        private string realmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string SystemCode
        {
            get
            {
                return this.systemCodeField;
            }
            set
            {
                this.systemCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Realm
        {
            get
            {
                return this.realmField;
            }
            set
            {
                this.realmField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Message/MessageHeader")]
        public BSAccountFundsTransferServiceReference.RequestHeaderType RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://co-opbank.co.ke/Banking/CanonicalDataModel/FundsTransfer/4.0", Order=0)]
        public BSAccountFundsTransferServiceReference.FundsTransferType FundsTransfer;
        
        public PostRequest()
        {
        }
        
        public PostRequest(BSAccountFundsTransferServiceReference.RequestHeaderType RequestHeader, BSAccountFundsTransferServiceReference.FundsTransferType FundsTransfer)
        {
            this.RequestHeader = RequestHeader;
            this.FundsTransfer = FundsTransfer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn://co-opbank.co.ke/CommonServices/Data/Message/MessageHeader")]
        public BSAccountFundsTransferServiceReference.ResponseHeaderType ResponseHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://co-opbank.co.ke/Banking/CanonicalDataModel/FundsTransfer/4.0", Order=0)]
        public BSAccountFundsTransferServiceReference.FundsTransferType FundsTransfer;
        
        public PostResponse()
        {
        }
        
        public PostResponse(BSAccountFundsTransferServiceReference.ResponseHeaderType ResponseHeader, BSAccountFundsTransferServiceReference.FundsTransferType FundsTransfer)
        {
            this.ResponseHeader = ResponseHeader;
            this.FundsTransfer = FundsTransfer;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface BSAccountChannel : BSAccountFundsTransferServiceReference.BSAccount, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class BSAccountClient : System.ServiceModel.ClientBase<BSAccountFundsTransferServiceReference.BSAccount>, BSAccountFundsTransferServiceReference.BSAccount
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BSAccountClient() : 
                base(BSAccountClient.GetDefaultBinding(), BSAccountClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BSAccountSOAP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BSAccountClient(EndpointConfiguration endpointConfiguration) : 
                base(BSAccountClient.GetBindingForEndpoint(endpointConfiguration), BSAccountClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BSAccountClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BSAccountClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BSAccountClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BSAccountClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BSAccountClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<BSAccountFundsTransferServiceReference.PostResponse> PostAsync(BSAccountFundsTransferServiceReference.PostRequest request)
        {
            return base.Channel.PostAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BSAccountSOAP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BSAccountSOAP))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/Account/FundsTransfer/SyncPost/4.0");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BSAccountClient.GetBindingForEndpoint(EndpointConfiguration.BSAccountSOAP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BSAccountClient.GetEndpointAddress(EndpointConfiguration.BSAccountSOAP);
        }
        
        public enum EndpointConfiguration
        {
            
            BSAccountSOAP,
        }
    }
}
