// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("AlertMessageType")]
    public partial class AlertMessageType
    {
        public AlertMessageType()
        {
            AlertMessageRegistries = new HashSet<AlertMessageRegistry>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; } = null!;
        [Column("description")]
        [StringLength(255)]
        public string? Description { get; set; }
        [Column("title")]
        [StringLength(255)]
        public string? Title { get; set; }
        [Column("email_content_template")]
        public string? EmailContentTemplate { get; set; }
        [Column("raw_email_content_template")]
        public string? RawEmailContentTemplate { get; set; }
        [Column("phone_content_template")]
        [StringLength(255)]
        public string? PhoneContentTemplate { get; set; }
        [Required]
        [Column("enabled")]
        public bool? Enabled { get; set; }

        [InverseProperty("AlertType")]
        public virtual ICollection<AlertMessageRegistry> AlertMessageRegistries { get; set; }
    }
}