// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("CITTransaction")]
    public partial class Cittransaction
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("datetime")]
        public DateTime Datetime { get; set; }
        [Column("CIT_id")]
        public Guid CitId { get; set; }
        [Column("currency")]
        [StringLength(3)]
        [Unicode(false)]
        public string Currency { get; set; } = null!;
        [Column("amount")]
        public long Amount { get; set; }
        [Column("suspense_account")]
        [StringLength(50)]
        public string SuspenseAccount { get; set; } = null!;
        [Column("account_number")]
        [StringLength(50)]
        public string AccountNumber { get; set; } = null!;
        [Column("narration")]
        [StringLength(50)]
        public string? Narration { get; set; }
        [Column("cb_tx_number")]
        [StringLength(50)]
        public string? CbTxNumber { get; set; }
        [Column("cb_date")]
        public DateTime? CbDate { get; set; }
        [Column("cb_tx_status")]
        [StringLength(50)]
        public string? CbTxStatus { get; set; }
        [Column("cb_status_detail")]
        public string? CbStatusDetail { get; set; }
        [Column("error_code")]
        public int ErrorCode { get; set; }
        [Column("error_message")]
        [StringLength(255)]
        public string? ErrorMessage { get; set; }

        [ForeignKey("CitId")]
        [InverseProperty("Cittransactions")]
        public virtual Cit Cit { get; set; } = null!;
    }
}