// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("Config")]
    [Index("CategoryId", Name = "icategory_id_Config")]
    public partial class Config
    {
        public Config()
        {
            DeviceConfigs = new HashSet<DeviceConfig>();
        }

        [Key]
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; } = null!;
        [Column("default_value")]
        public string? DefaultValue { get; set; }
        [Column("description")]
        [StringLength(255)]
        public string? Description { get; set; }
        [Column("category_id")]
        public Guid CategoryId { get; set; }

        [ForeignKey("CategoryId")]
        [InverseProperty("Configs")]
        public virtual ConfigCategory Category { get; set; } = null!;
        [InverseProperty("Config")]
        public virtual ICollection<DeviceConfig> DeviceConfigs { get; set; }
    }
}