// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("CurrencyList_Currency")]
    [Index("CurrencyList", "CurrencyItem", Name = "UX_CurrencyList_Currency_CurrencyItem", IsUnique = true)]
    [Index("CurrencyList", "CurrencyOrder", Name = "UX_Currency_CurrencyList_Order", IsUnique = true)]
    [Index("CurrencyItem", Name = "icurrency_item_CurrencyList_Currency")]
    [Index("CurrencyList", Name = "icurrency_list_CurrencyList_Currency")]
    public partial class CurrencyListCurrency
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("currency_list")]
        public int CurrencyList { get; set; }
        [Column("currency_item")]
        [StringLength(3)]
        [Unicode(false)]
        public string CurrencyItem { get; set; } = null!;
        [Column("currency_order")]
        public int CurrencyOrder { get; set; }
        [Column("max_value")]
        public long MaxValue { get; set; }
        [Column("max_count")]
        public int MaxCount { get; set; }

        [ForeignKey("CurrencyItem")]
        [InverseProperty("CurrencyListCurrencies")]
        public virtual Currency CurrencyItemNavigation { get; set; } = null!;
        [ForeignKey("CurrencyList")]
        [InverseProperty("CurrencyListCurrencies")]
        public virtual CurrencyList CurrencyListNavigation { get; set; } = null!;
    }
}