// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Index("DeviceId", Name = "idevice_id_DeviceStatus")]
    public partial class DeviceStatu
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("device_id")]
        public Guid DeviceId { get; set; }
        [Column("controller_state")]
        [StringLength(20)]
        public string ControllerState { get; set; } = null!;
        [Column("ba_type")]
        [StringLength(20)]
        public string BaType { get; set; } = null!;
        [Column("ba_status")]
        [StringLength(20)]
        public string BaStatus { get; set; } = null!;
        [Column("ba_currency")]
        [StringLength(3)]
        [Unicode(false)]
        public string BaCurrency { get; set; } = null!;
        [Column("bag_number")]
        [StringLength(50)]
        public string BagNumber { get; set; } = null!;
        [Column("bag_status")]
        [StringLength(20)]
        public string BagStatus { get; set; } = null!;
        [Column("bag_note_level")]
        public int BagNoteLevel { get; set; }
        [Column("bag_note_capacity")]
        [StringLength(10)]
        public string BagNoteCapacity { get; set; } = null!;
        [Column("bag_value_level")]
        public long? BagValueLevel { get; set; }
        [Column("bag_value_capacity")]
        public long? BagValueCapacity { get; set; }
        [Column("bag_percent_full")]
        public int BagPercentFull { get; set; }
        [Column("sensors_type")]
        [StringLength(20)]
        public string SensorsType { get; set; } = null!;
        [Column("sensors_status")]
        [StringLength(20)]
        public string SensorsStatus { get; set; } = null!;
        [Column("sensors_value")]
        public int SensorsValue { get; set; }
        [Column("sensors_door")]
        [StringLength(20)]
        public string SensorsDoor { get; set; } = null!;
        [Column("sensors_bag")]
        [StringLength(20)]
        public string SensorsBag { get; set; } = null!;
        [Column("escrow_type")]
        [StringLength(20)]
        public string EscrowType { get; set; } = null!;
        [Column("escrow_status")]
        [StringLength(20)]
        public string EscrowStatus { get; set; } = null!;
        [Column("escrow_position")]
        [StringLength(20)]
        public string EscrowPosition { get; set; } = null!;
        [Column("transaction_status")]
        [StringLength(20)]
        public string? TransactionStatus { get; set; }
        [Column("transaction_type")]
        [StringLength(20)]
        public string? TransactionType { get; set; }
        [Column("machine_datetime")]
        public DateTime? MachineDatetime { get; set; }
        [Column("current_status")]
        public int CurrentStatus { get; set; }
        [Column("modified")]
        public DateTime? Modified { get; set; }
        [Column("machine_name")]
        [StringLength(50)]
        public string MachineName { get; set; } = null!;
    }
}