// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace Sample.Entities
{
    public partial class GetDestinationEmailsByAlertTypeResult
    {
        public string? email { get; set; }
    }
}
