// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("GUIPrepopList_Item")]
    [Index("Item", "List", Name = "UX_GUIPrepopList_Item", IsUnique = true)]
    [Index("Item", Name = "iItem_GUIPrepopList_Item")]
    [Index("List", Name = "iList_GUIPrepopList_Item")]
    public partial class GUIPrepopListItem
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        public Guid List { get; set; }
        public Guid Item { get; set; }
        [Column("List_Order")]
        public int ListOrder { get; set; }

        [ForeignKey("Item")]
        [InverseProperty("GUIPrepopListItems")]
        public virtual GUIPrepopItem ItemNavigation { get; set; } = null!;
        [ForeignKey("List")]
        [InverseProperty("GUIPrepopListItems")]
        public virtual GUIPrepopList ListNavigation { get; set; } = null!;
    }
}