// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("GUIScreenText")]
    [Index("GUIScreenId", Name = "UX_GUIScreenText_gui_screen_id", IsUnique = true)]
    [Index("BtnAcceptCaption", Name = "ibtn_accept_caption_GUIScreenText")]
    [Index("BtnBackCaption", Name = "ibtn_back_caption_GUIScreenText")]
    [Index("BtnCancelCaption", Name = "ibtn_cancel_caption_GUIScreenText")]
    [Index("FullInstructions", Name = "ifull_instructions_GUIScreenText")]
    [Index("GUIScreenId", Name = "iguiscreen_id_GUIScreenText")]
    [Index("ScreenTitle", Name = "iscreen_title_GUIScreenText")]
    [Index("ScreenTitleInstruction", Name = "iscreen_title_instruction_GUIScreenText")]
    public partial class GUIScreenText
    {
        public GUIScreenText()
        {
            GUIScreens = new HashSet<GUIScreen>();
        }

        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("guiscreen_id")]
        public int GUIScreenId { get; set; }
        [Column("screen_title")]
        public Guid ScreenTitle { get; set; }
        [Column("screen_title_instruction")]
        public Guid? ScreenTitleInstruction { get; set; }
        [Column("full_instructions")]
        public Guid? FullInstructions { get; set; }
        [Column("btn_accept_caption")]
        public Guid? BtnAcceptCaption { get; set; }
        [Column("btn_back_caption")]
        public Guid? BtnBackCaption { get; set; }
        [Column("btn_cancel_caption")]
        public Guid? BtnCancelCaption { get; set; }

        [ForeignKey("BtnAcceptCaption")]
        [InverseProperty("GUIScreenTextBtnAcceptCaptionNavigations")]
        public virtual TextItem? BtnAcceptCaptionNavigation { get; set; }
        [ForeignKey("BtnBackCaption")]
        [InverseProperty("GUIScreenTextBtnBackCaptionNavigations")]
        public virtual TextItem? BtnBackCaptionNavigation { get; set; }
        [ForeignKey("BtnCancelCaption")]
        [InverseProperty("GUIScreenTextBtnCancelCaptionNavigations")]
        public virtual TextItem? BtnCancelCaptionNavigation { get; set; }
        [ForeignKey("FullInstructions")]
        [InverseProperty("GUIScreenTextFullInstructionsNavigations")]
        public virtual TextItem? FullInstructionsNavigation { get; set; }
        [ForeignKey("GUIScreenId")]
        [InverseProperty("GUIScreenText")]
        public virtual GUIScreen GUIScreen { get; set; } = null!;
        [ForeignKey("ScreenTitleInstruction")]
        [InverseProperty("GUIScreenTextScreenTitleInstructionNavigations")]
        public virtual TextItem? ScreenTitleInstructionNavigation { get; set; }
        [ForeignKey("ScreenTitle")]
        [InverseProperty("GUIScreenTextScreenTitleNavigations")]
        public virtual TextItem ScreenTitleNavigation { get; set; } = null!;
        [InverseProperty("GuiTextNavigation")]
        public virtual ICollection<GUIScreen> GUIScreens { get; set; }
    }
}