// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("GUIScreenList")]
    public partial class GUIScreenList
    {
        public GUIScreenList()
        {
            Devices = new HashSet<Device>();
            GuiScreenListScreens = new HashSet<GuiScreenListScreen>();
            TransactionTypeListItems = new HashSet<TransactionTypeListItem>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; } = null!;
        [Column("description")]
        [StringLength(255)]
        public string? Description { get; set; }
        [Column("enabled")]
        public bool Enabled { get; set; }

        [InverseProperty("GUIScreenListNavigation")]
        public virtual ICollection<Device> Devices { get; set; }
        [InverseProperty("GuiScreenListNavigation")]
        public virtual ICollection<GuiScreenListScreen> GuiScreenListScreens { get; set; }
        [InverseProperty("TxTypeGUIScreenlistNavigation")]
        public virtual ICollection<TransactionTypeListItem> TransactionTypeListItems { get; set; }
    }
}