// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("sysTextItemCategory", Schema = "xlns")]
    [Index("Name", Name = "UX_TextItemCategory_name", IsUnique = true)]
    [Index("Parent", Name = "iParent_xlns_sysTextItemCategory_51488F7B")]
    public partial class SysTextItemCategory
    {
        public SysTextItemCategory()
        {
            InverseParentNavigation = new HashSet<SysTextItemCategory>();
            SysTextItems = new HashSet<SysTextItem>();
        }

        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; } = null!;
        [Column("description")]
        [StringLength(255)]
        public string? Description { get; set; }
        public Guid? Parent { get; set; }

        [ForeignKey("Parent")]
        [InverseProperty("InverseParentNavigation")]
        public virtual SysTextItemCategory? ParentNavigation { get; set; }
        [InverseProperty("ParentNavigation")]
        public virtual ICollection<SysTextItemCategory> InverseParentNavigation { get; set; }
        [InverseProperty("CategoryNavigation")]
        public virtual ICollection<SysTextItem> SysTextItems { get; set; }
    }
}