// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("TextTranslation", Schema = "xlns")]
    [Index("LanguageCode", "TextItemId", Name = "UX_UI_Translation_Language_Pair", IsUnique = true)]
    [Index("LanguageCode", Name = "iLanguageCode_xlns_TextTranslation_0EDE47B6")]
    [Index("TextItemId", Name = "iTextItemID_xlns_TextTranslation_00B6C5AC")]
    public partial class TextTranslation
    {
        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("TextItemID")]
        public Guid TextItemId { get; set; }
        [StringLength(5)]
        [Unicode(false)]
        public string LanguageCode { get; set; } = null!;
        public string TranslationText { get; set; } = null!;

        [ForeignKey("LanguageCode")]
        [InverseProperty("TextTranslations")]
        public virtual Language LanguageCodeNavigation { get; set; } = null!;
        [ForeignKey("TextItemId")]
        [InverseProperty("TextTranslations")]
        public virtual TextItem TextItem { get; set; } = null!;
    }
}