// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("TextItemCategory", Schema = "xlns")]
    [Index("Name", Name = "UX_UI_TextItemCategory_name", IsUnique = true)]
    [Index("Parent", Name = "iParent_xlns_TextItemCategory_051D04A6")]
    public partial class TextItemCategory
    {
        public TextItemCategory()
        {
            InverseParentNavigation = new HashSet<TextItemCategory>();
            TextItems = new HashSet<TextItem>();
        }

        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; } = null!;
        [Column("description")]
        [StringLength(255)]
        public string? Description { get; set; }
        public Guid? Parent { get; set; }

        [ForeignKey("Parent")]
        [InverseProperty("InverseParentNavigation")]
        public virtual TextItemCategory? ParentNavigation { get; set; }
        [InverseProperty("ParentNavigation")]
        public virtual ICollection<TextItemCategory> InverseParentNavigation { get; set; }
        [InverseProperty("CategoryNavigation")]
        public virtual ICollection<TextItem> TextItems { get; set; }
    }
}