// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("TextItem", Schema = "xlns")]
    [Index("Name", "Category", Name = "UX_UI_TextItem_name", IsUnique = true)]
    [Index("Category", Name = "iCategory_xlns_TextItem_CDE8C5ED")]
    [Index("TextItemTypeId", Name = "iTextItemTypeID_xlns_TextItem_2A2E0516")]
    public partial class TextItem
    {
        public TextItem()
        {
            GUIPrepopItems = new HashSet<GUIPrepopItem>();
            GUIScreenTextBtnAcceptCaptionNavigations = new HashSet<GUIScreenText>();
            GUIScreenTextBtnBackCaptionNavigations = new HashSet<GUIScreenText>();
            GUIScreenTextBtnCancelCaptionNavigations = new HashSet<GUIScreenText>();
            GUIScreenTextFullInstructionsNavigations = new HashSet<GUIScreenText>();
            GUIScreenTextScreenTitleInstructionNavigations = new HashSet<GUIScreenText>();
            GUIScreenTextScreenTitleNavigations = new HashSet<GUIScreenText>();
            TextTranslations = new HashSet<TextTranslation>();
            TransactionTextAccountNameCaptionNavigations = new HashSet<TransactionText>();
            TransactionTextAccountNumberCaptionNavigations = new HashSet<TransactionText>();
            TransactionTextAliasAccountNameCaptionNavigations = new HashSet<TransactionText>();
            TransactionTextAliasAccountNumberCaptionNavigations = new HashSet<TransactionText>();
            TransactionTextDepositorNameCaptionNavigations = new HashSet<TransactionText>();
            TransactionTextDisclaimerNavigations = new HashSet<TransactionText>();
            TransactionTextFullInstructionsNavigations = new HashSet<TransactionText>();
            TransactionTextFundsSourceCaptionNavigations = new HashSet<TransactionText>();
            TransactionTextIdNumberCaptionNavigations = new HashSet<TransactionText>();
            TransactionTextListItemCaptionNavigations = new HashSet<TransactionText>();
            TransactionTextNarrationCaptionNavigations = new HashSet<TransactionText>();
            TransactionTextPhoneNumberCaptionNavigations = new HashSet<TransactionText>();
            TransactionTextReceiptTemplateNavigations = new HashSet<TransactionText>();
            TransactionTextReferenceAccountNameCaptionNavigations = new HashSet<TransactionText>();
            TransactionTextReferenceAccountNumberCaptionNavigations = new HashSet<TransactionText>();
            TransactionTextTermsNavigations = new HashSet<TransactionText>();
            ValidationTextErrorMessageNavigations = new HashSet<ValidationText>();
            ValidationTextSuccessMessageNavigations = new HashSet<ValidationText>();
        }

        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [StringLength(50)]
        public string Name { get; set; } = null!;
        [StringLength(255)]
        public string? Description { get; set; }
        public string DefaultTranslation { get; set; } = null!;
        public Guid Category { get; set; }
        [Column("TextItemTypeID")]
        public Guid? TextItemTypeId { get; set; }

        [ForeignKey("Category")]
        [InverseProperty("TextItems")]
        public virtual TextItemCategory CategoryNavigation { get; set; } = null!;
        [ForeignKey("TextItemTypeId")]
        [InverseProperty("TextItems")]
        public virtual TextItemType? TextItemType { get; set; }
        [InverseProperty("ValueNavigation")]
        public virtual ICollection<GUIPrepopItem> GUIPrepopItems { get; set; }
        [InverseProperty("BtnAcceptCaptionNavigation")]
        public virtual ICollection<GUIScreenText> GUIScreenTextBtnAcceptCaptionNavigations { get; set; }
        [InverseProperty("BtnBackCaptionNavigation")]
        public virtual ICollection<GUIScreenText> GUIScreenTextBtnBackCaptionNavigations { get; set; }
        [InverseProperty("BtnCancelCaptionNavigation")]
        public virtual ICollection<GUIScreenText> GUIScreenTextBtnCancelCaptionNavigations { get; set; }
        [InverseProperty("FullInstructionsNavigation")]
        public virtual ICollection<GUIScreenText> GUIScreenTextFullInstructionsNavigations { get; set; }
        [InverseProperty("ScreenTitleInstructionNavigation")]
        public virtual ICollection<GUIScreenText> GUIScreenTextScreenTitleInstructionNavigations { get; set; }
        [InverseProperty("ScreenTitleNavigation")]
        public virtual ICollection<GUIScreenText> GUIScreenTextScreenTitleNavigations { get; set; }
        [InverseProperty("TextItem")]
        public virtual ICollection<TextTranslation> TextTranslations { get; set; }
        [InverseProperty("AccountNameCaptionNavigation")]
        public virtual ICollection<TransactionText> TransactionTextAccountNameCaptionNavigations { get; set; }
        [InverseProperty("AccountNumberCaptionNavigation")]
        public virtual ICollection<TransactionText> TransactionTextAccountNumberCaptionNavigations { get; set; }
        [InverseProperty("AliasAccountNameCaptionNavigation")]
        public virtual ICollection<TransactionText> TransactionTextAliasAccountNameCaptionNavigations { get; set; }
        [InverseProperty("AliasAccountNumberCaptionNavigation")]
        public virtual ICollection<TransactionText> TransactionTextAliasAccountNumberCaptionNavigations { get; set; }
        [InverseProperty("DepositorNameCaptionNavigation")]
        public virtual ICollection<TransactionText> TransactionTextDepositorNameCaptionNavigations { get; set; }
        [InverseProperty("DisclaimerNavigation")]
        public virtual ICollection<TransactionText> TransactionTextDisclaimerNavigations { get; set; }
        [InverseProperty("FullInstructionsNavigation")]
        public virtual ICollection<TransactionText> TransactionTextFullInstructionsNavigations { get; set; }
        [InverseProperty("FundsSourceCaptionNavigation")]
        public virtual ICollection<TransactionText> TransactionTextFundsSourceCaptionNavigations { get; set; }
        [InverseProperty("IdNumberCaptionNavigation")]
        public virtual ICollection<TransactionText> TransactionTextIdNumberCaptionNavigations { get; set; }
        [InverseProperty("ListItemCaptionNavigation")]
        public virtual ICollection<TransactionText> TransactionTextListItemCaptionNavigations { get; set; }
        [InverseProperty("NarrationCaptionNavigation")]
        public virtual ICollection<TransactionText> TransactionTextNarrationCaptionNavigations { get; set; }
        [InverseProperty("PhoneNumberCaptionNavigation")]
        public virtual ICollection<TransactionText> TransactionTextPhoneNumberCaptionNavigations { get; set; }
        [InverseProperty("ReceiptTemplateNavigation")]
        public virtual ICollection<TransactionText> TransactionTextReceiptTemplateNavigations { get; set; }
        [InverseProperty("ReferenceAccountNameCaptionNavigation")]
        public virtual ICollection<TransactionText> TransactionTextReferenceAccountNameCaptionNavigations { get; set; }
        [InverseProperty("ReferenceAccountNumberCaptionNavigation")]
        public virtual ICollection<TransactionText> TransactionTextReferenceAccountNumberCaptionNavigations { get; set; }
        [InverseProperty("TermsNavigation")]
        public virtual ICollection<TransactionText> TransactionTextTermsNavigations { get; set; }
        [InverseProperty("ErrorMessageNavigation")]
        public virtual ICollection<ValidationText> ValidationTextErrorMessageNavigations { get; set; }
        [InverseProperty("SuccessMessageNavigation")]
        public virtual ICollection<ValidationText> ValidationTextSuccessMessageNavigations { get; set; }
    }
}