// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("UserGroup")]
    [Index("ParentGroup", Name = "iparent_group_UserGroup")]
    public partial class UserGroup
    {
        public UserGroup()
        {
            ApplicationUsers = new HashSet<ApplicationUser>();
            Devices = new HashSet<Device>();
            InverseParentGroupNavigation = new HashSet<UserGroup>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; } = null!;
        [Column("description")]
        [StringLength(512)]
        public string? Description { get; set; }
        [Column("parent_group")]
        public int? ParentGroup { get; set; }

        [ForeignKey("ParentGroup")]
        [InverseProperty("InverseParentGroupNavigation")]
        public virtual UserGroup? ParentGroupNavigation { get; set; }
        [InverseProperty("UserGroupNavigation")]
        public virtual ICollection<ApplicationUser> ApplicationUsers { get; set; }
        [InverseProperty("UserGroupNavigation")]
        public virtual ICollection<Device> Devices { get; set; }
        [InverseProperty("ParentGroupNavigation")]
        public virtual ICollection<UserGroup> InverseParentGroupNavigation { get; set; }
    }
}