// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("ValidationText")]
    [Index("ErrorMessage", Name = "ierror_message_ValidationText")]
    [Index("SuccessMessage", Name = "isuccess_message_ValidationText")]
    [Index("ValidationItemId", Name = "ivalidation_item_id_ValidationText")]
    public partial class ValidationText
    {
        public ValidationText()
        {
            ValidationItems = new HashSet<ValidationItem>();
        }

        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("validation_item_id")]
        public Guid ValidationItemId { get; set; }
        [Column("error_message")]
        public Guid? ErrorMessage { get; set; }
        [Column("success_message")]
        public Guid? SuccessMessage { get; set; }

        [ForeignKey("ErrorMessage")]
        [InverseProperty("ValidationTextErrorMessageNavigations")]
        public virtual TextItem? ErrorMessageNavigation { get; set; }
        [ForeignKey("SuccessMessage")]
        [InverseProperty("ValidationTextSuccessMessageNavigations")]
        public virtual TextItem? SuccessMessageNavigation { get; set; }
        [ForeignKey("ValidationItemId")]
        [InverseProperty("ValidationTexts")]
        public virtual ValidationItem ValidationItem { get; set; } = null!;
        [InverseProperty("ValidationText")]
        public virtual ICollection<ValidationItem> ValidationItems { get; set; }
    }
}