// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sample.Entities
{
    [Table("ValidationItem")]
    [Index("TypeId", Name = "itype_id_ValidationItem")]
    [Index("ValidationTextId", Name = "ivalidation_text_id_ValidationItem")]
    public partial class ValidationItem
    {
        public ValidationItem()
        {
            ValidationItemValues = new HashSet<ValidationItemValue>();
            ValidationListValidationItems = new HashSet<ValidationListValidationItem>();
            ValidationTexts = new HashSet<ValidationText>();
        }

        [Key]
        [Column("id")]
        public Guid Id { get; set; }
        [Column("name")]
        [StringLength(50)]
        public string Name { get; set; } = null!;
        [Column("category")]
        [StringLength(10)]
        public string? Category { get; set; }
        [Column("description")]
        [StringLength(255)]
        public string? Description { get; set; }
        [Column("type_id")]
        public Guid TypeId { get; set; }
        [Column("enabled")]
        public bool Enabled { get; set; }
        [Column("error_code")]
        public int? ErrorCode { get; set; }
        [Column("validation_text_id")]
        public Guid? ValidationTextId { get; set; }

        [ForeignKey("TypeId")]
        [InverseProperty("ValidationItems")]
        public virtual ValidationType Type { get; set; } = null!;
        [ForeignKey("ValidationTextId")]
        [InverseProperty("ValidationItems")]
        public virtual ValidationText? ValidationText { get; set; }
        [InverseProperty("ValidationItem")]
        public virtual ICollection<ValidationItemValue> ValidationItemValues { get; set; }
        [InverseProperty("ValidationItem")]
        public virtual ICollection<ValidationListValidationItem> ValidationListValidationItems { get; set; }
        [InverseProperty("ValidationItem")]
        public virtual ICollection<ValidationText> ValidationTexts { get; set; }
    }
}